<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_UserLogin.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_BuffInfo</code>
 */
class PB_BuffInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *Buff类型
     *
     * Generated from protobuf field <code>int32 buff = 1;</code>
     */
    private $buff = 0;
    /**
     *失效时间
     *
     * Generated from protobuf field <code>int64 expire = 2;</code>
     */
    private $expire = 0;
    /**
     *其他属性(json)
     *
     * Generated from protobuf field <code>string options = 3;</code>
     */
    private $options = '';

    public function __construct() {
        \GPBMetadata\PBUserLogin::initOnce();
        parent::__construct();
    }

    /**
     *Buff类型
     *
     * Generated from protobuf field <code>int32 buff = 1;</code>
     * @return int
     */
    public function getBuff()
    {
        return $this->buff;
    }

    /**
     *Buff类型
     *
     * Generated from protobuf field <code>int32 buff = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setBuff($var)
    {
        GPBUtil::checkInt32($var);
        $this->buff = $var;

        return $this;
    }

    /**
     *失效时间
     *
     * Generated from protobuf field <code>int64 expire = 2;</code>
     * @return int|string
     */
    public function getExpire()
    {
        return $this->expire;
    }

    /**
     *失效时间
     *
     * Generated from protobuf field <code>int64 expire = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpire($var)
    {
        GPBUtil::checkInt64($var);
        $this->expire = $var;

        return $this;
    }

    /**
     *其他属性(json)
     *
     * Generated from protobuf field <code>string options = 3;</code>
     * @return string
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     *其他属性(json)
     *
     * Generated from protobuf field <code>string options = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkString($var, True);
        $this->options = $var;

        return $this;
    }

}

