<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_BetOption.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_BetOption</code>
 */
class PB_BetOption extends \Google\Protobuf\Internal\Message
{
    /**
     *下注倍数
     *
     * Generated from protobuf field <code>int64 betMultiple = 1;</code>
     */
    private $betMultiple = 0;
    /**
     *下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 2;</code>
     */
    private $totalBet = 0;

    public function __construct() {
        \GPBMetadata\PBBetOption::initOnce();
        parent::__construct();
    }

    /**
     *下注倍数
     *
     * Generated from protobuf field <code>int64 betMultiple = 1;</code>
     * @return int|string
     */
    public function getBetMultiple()
    {
        return $this->betMultiple;
    }

    /**
     *下注倍数
     *
     * Generated from protobuf field <code>int64 betMultiple = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBetMultiple($var)
    {
        GPBUtil::checkInt64($var);
        $this->betMultiple = $var;

        return $this;
    }

    /**
     *下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 2;</code>
     * @return int|string
     */
    public function getTotalBet()
    {
        return $this->totalBet;
    }

    /**
     *下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalBet($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalBet = $var;

        return $this;
    }

}

