<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_CheckModuleVersion.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_CheckModuleVersion_Res</code>
 */
class PB_CheckModuleVersion_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *模块名称
     *
     * Generated from protobuf field <code>string module = 1;</code>
     */
    private $module = '';
    /**
     *最新小版本号
     *
     * Generated from protobuf field <code>int32 version = 2;</code>
     */
    private $version = 0;
    /**
     *更新包地址
     *
     * Generated from protobuf field <code>string packageUrl = 3;</code>
     */
    private $packageUrl = '';
    /**
     *是否有更新
     *
     * Generated from protobuf field <code>bool hasUpdate = 4;</code>
     */
    private $hasUpdate = false;
    /**
     *更新包MD5值
     *
     * Generated from protobuf field <code>string md5 = 5;</code>
     */
    private $md5 = '';

    public function __construct() {
        \GPBMetadata\PBCheckModuleVersion::initOnce();
        parent::__construct();
    }

    /**
     *模块名称
     *
     * Generated from protobuf field <code>string module = 1;</code>
     * @return string
     */
    public function getModule()
    {
        return $this->module;
    }

    /**
     *模块名称
     *
     * Generated from protobuf field <code>string module = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setModule($var)
    {
        GPBUtil::checkString($var, True);
        $this->module = $var;

        return $this;
    }

    /**
     *最新小版本号
     *
     * Generated from protobuf field <code>int32 version = 2;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     *最新小版本号
     *
     * Generated from protobuf field <code>int32 version = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     *更新包地址
     *
     * Generated from protobuf field <code>string packageUrl = 3;</code>
     * @return string
     */
    public function getPackageUrl()
    {
        return $this->packageUrl;
    }

    /**
     *更新包地址
     *
     * Generated from protobuf field <code>string packageUrl = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPackageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->packageUrl = $var;

        return $this;
    }

    /**
     *是否有更新
     *
     * Generated from protobuf field <code>bool hasUpdate = 4;</code>
     * @return bool
     */
    public function getHasUpdate()
    {
        return $this->hasUpdate;
    }

    /**
     *是否有更新
     *
     * Generated from protobuf field <code>bool hasUpdate = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasUpdate($var)
    {
        GPBUtil::checkBool($var);
        $this->hasUpdate = $var;

        return $this;
    }

    /**
     *更新包MD5值
     *
     * Generated from protobuf field <code>string md5 = 5;</code>
     * @return string
     */
    public function getMd5()
    {
        return $this->md5;
    }

    /**
     *更新包MD5值
     *
     * Generated from protobuf field <code>string md5 = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMd5($var)
    {
        GPBUtil::checkString($var, True);
        $this->md5 = $var;

        return $this;
    }

}

