<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_CollectInfo.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_CollectInfo</code>
 */
class PB_CollectInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *所处节点编号
     *
     * Generated from protobuf field <code>int32 node = 1;</code>
     */
    private $node = 0;
    /**
     *解锁所需下注额
     *
     * Generated from protobuf field <code>int32 unlockBet = 2;</code>
     */
    private $unlockBet = 0;
    /**
     *收集类型(TotalBet|MachineItem)
     *
     * Generated from protobuf field <code>string collectType = 3;</code>
     */
    private $collectType = '';
    /**
     *收集元素ID列表(如果是收集机台元素的话)
     *
     * Generated from protobuf field <code>repeated string collectItems = 4;</code>
     */
    private $collectItems;
    /**
     *拥有的Booster(json:{"I1401":5})
     *
     * Generated from protobuf field <code>string boosters = 5;</code>
     */
    private $boosters = '';
    /**
     *收集期间下注均值
     *
     * Generated from protobuf field <code>int64 avgBet = 6;</code>
     */
    private $avgBet = 0;
    /**
     *收集期间累积值
     *
     * Generated from protobuf field <code>int64 value = 7;</code>
     */
    private $value = 0;
    /**
     *当前进度值
     *
     * Generated from protobuf field <code>int64 progress = 8;</code>
     */
    private $progress = 0;
    /**
     *所需总进度值
     *
     * Generated from protobuf field <code>int64 target = 9;</code>
     */
    private $target = 0;
    /**
     *是否完成收集
     *
     * Generated from protobuf field <code>bool complete = 10;</code>
     */
    private $complete = false;

    public function __construct() {
        \GPBMetadata\PBCollectInfo::initOnce();
        parent::__construct();
    }

    /**
     *所处节点编号
     *
     * Generated from protobuf field <code>int32 node = 1;</code>
     * @return int
     */
    public function getNode()
    {
        return $this->node;
    }

    /**
     *所处节点编号
     *
     * Generated from protobuf field <code>int32 node = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNode($var)
    {
        GPBUtil::checkInt32($var);
        $this->node = $var;

        return $this;
    }

    /**
     *解锁所需下注额
     *
     * Generated from protobuf field <code>int32 unlockBet = 2;</code>
     * @return int
     */
    public function getUnlockBet()
    {
        return $this->unlockBet;
    }

    /**
     *解锁所需下注额
     *
     * Generated from protobuf field <code>int32 unlockBet = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUnlockBet($var)
    {
        GPBUtil::checkInt32($var);
        $this->unlockBet = $var;

        return $this;
    }

    /**
     *收集类型(TotalBet|MachineItem)
     *
     * Generated from protobuf field <code>string collectType = 3;</code>
     * @return string
     */
    public function getCollectType()
    {
        return $this->collectType;
    }

    /**
     *收集类型(TotalBet|MachineItem)
     *
     * Generated from protobuf field <code>string collectType = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCollectType($var)
    {
        GPBUtil::checkString($var, True);
        $this->collectType = $var;

        return $this;
    }

    /**
     *收集元素ID列表(如果是收集机台元素的话)
     *
     * Generated from protobuf field <code>repeated string collectItems = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCollectItems()
    {
        return $this->collectItems;
    }

    /**
     *收集元素ID列表(如果是收集机台元素的话)
     *
     * Generated from protobuf field <code>repeated string collectItems = 4;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCollectItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->collectItems = $arr;

        return $this;
    }

    /**
     *拥有的Booster(json:{"I1401":5})
     *
     * Generated from protobuf field <code>string boosters = 5;</code>
     * @return string
     */
    public function getBoosters()
    {
        return $this->boosters;
    }

    /**
     *拥有的Booster(json:{"I1401":5})
     *
     * Generated from protobuf field <code>string boosters = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBoosters($var)
    {
        GPBUtil::checkString($var, True);
        $this->boosters = $var;

        return $this;
    }

    /**
     *收集期间下注均值
     *
     * Generated from protobuf field <code>int64 avgBet = 6;</code>
     * @return int|string
     */
    public function getAvgBet()
    {
        return $this->avgBet;
    }

    /**
     *收集期间下注均值
     *
     * Generated from protobuf field <code>int64 avgBet = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAvgBet($var)
    {
        GPBUtil::checkInt64($var);
        $this->avgBet = $var;

        return $this;
    }

    /**
     *收集期间累积值
     *
     * Generated from protobuf field <code>int64 value = 7;</code>
     * @return int|string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     *收集期间累积值
     *
     * Generated from protobuf field <code>int64 value = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->value = $var;

        return $this;
    }

    /**
     *当前进度值
     *
     * Generated from protobuf field <code>int64 progress = 8;</code>
     * @return int|string
     */
    public function getProgress()
    {
        return $this->progress;
    }

    /**
     *当前进度值
     *
     * Generated from protobuf field <code>int64 progress = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProgress($var)
    {
        GPBUtil::checkInt64($var);
        $this->progress = $var;

        return $this;
    }

    /**
     *所需总进度值
     *
     * Generated from protobuf field <code>int64 target = 9;</code>
     * @return int|string
     */
    public function getTarget()
    {
        return $this->target;
    }

    /**
     *所需总进度值
     *
     * Generated from protobuf field <code>int64 target = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTarget($var)
    {
        GPBUtil::checkInt64($var);
        $this->target = $var;

        return $this;
    }

    /**
     *是否完成收集
     *
     * Generated from protobuf field <code>bool complete = 10;</code>
     * @return bool
     */
    public function getComplete()
    {
        return $this->complete;
    }

    /**
     *是否完成收集
     *
     * Generated from protobuf field <code>bool complete = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setComplete($var)
    {
        GPBUtil::checkBool($var);
        $this->complete = $var;

        return $this;
    }

}

