<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_CheckModuleVersion.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_CheckModuleVersion_Req</code>
 */
class PB_CheckModuleVersion_Req extends \Google\Protobuf\Internal\Message
{
    /**
     *应用ID
     *
     * Generated from protobuf field <code>string appId = 1;</code>
     */
    private $appId = '';
    /**
     *模块名称
     *
     * Generated from protobuf field <code>string module = 2;</code>
     */
    private $module = '';
    /**
     *大版本号
     *
     * Generated from protobuf field <code>string bigVersion = 3;</code>
     */
    private $bigVersion = '';
    /**
     *小版本号
     *
     * Generated from protobuf field <code>int32 version = 4;</code>
     */
    private $version = 0;

    public function __construct() {
        \GPBMetadata\PBCheckModuleVersion::initOnce();
        parent::__construct();
    }

    /**
     *应用ID
     *
     * Generated from protobuf field <code>string appId = 1;</code>
     * @return string
     */
    public function getAppId()
    {
        return $this->appId;
    }

    /**
     *应用ID
     *
     * Generated from protobuf field <code>string appId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAppId($var)
    {
        GPBUtil::checkString($var, True);
        $this->appId = $var;

        return $this;
    }

    /**
     *模块名称
     *
     * Generated from protobuf field <code>string module = 2;</code>
     * @return string
     */
    public function getModule()
    {
        return $this->module;
    }

    /**
     *模块名称
     *
     * Generated from protobuf field <code>string module = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setModule($var)
    {
        GPBUtil::checkString($var, True);
        $this->module = $var;

        return $this;
    }

    /**
     *大版本号
     *
     * Generated from protobuf field <code>string bigVersion = 3;</code>
     * @return string
     */
    public function getBigVersion()
    {
        return $this->bigVersion;
    }

    /**
     *大版本号
     *
     * Generated from protobuf field <code>string bigVersion = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBigVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->bigVersion = $var;

        return $this;
    }

    /**
     *小版本号
     *
     * Generated from protobuf field <code>int32 version = 4;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     *小版本号
     *
     * Generated from protobuf field <code>int32 version = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

}

