<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_EnterMachine.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_EnterMachine_Res</code>
 */
class PB_EnterMachine_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *机台ID
     *
     * Generated from protobuf field <code>int32 machineId = 1;</code>
     */
    private $machineId = 0;
    /**
     *当前下注倍数
     *
     * Generated from protobuf field <code>int32 betMultiple = 2;</code>
     */
    private $betMultiple = 0;
    /**
     *当前下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 3;</code>
     */
    private $totalBet = 0;
    /**
     *待恢复下注额
     *
     * Generated from protobuf field <code>int64 resumeBet = 4;</code>
     */
    private $resumeBet = 0;
    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 5;</code>
     */
    private $totalWin = 0;
    /**
     *用户金币余额
     *
     * Generated from protobuf field <code>int64 coins = 6;</code>
     */
    private $coins = 0;
    /**
     *用户gem余额
     *
     * Generated from protobuf field <code>int64 gem = 7;</code>
     */
    private $gem = 0;
    /**
     *feature信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_FeatureInfo featureInfo = 8;</code>
     */
    private $featureInfo = null;
    /**
     *机台初始化元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 9;</code>
     */
    private $elements;
    /**
     *轴上悬浮的元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement stickyElements = 10;</code>
     */
    private $stickyElements;
    /**
     *解锁下注倍数选项
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BetOption betOptions = 11;</code>
     */
    private $betOptions;
    /**
     *ultra下注倍数选项
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BetOption ultraBetOptions = 12;</code>
     */
    private $ultraBetOptions;
    /**
     *全部下注倍数选项
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BetOption allBetOptions = 13;</code>
     */
    private $allBetOptions;
    /**
     *下次spin轴上的stack替换元素
     *
     * Generated from protobuf field <code>repeated string nextStacks = 14;</code>
     */
    private $nextStacks;
    /**
     * 消息
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_MessageBase64List nextMessages = 15;</code>
     */
    private $nextMessages;

    public function __construct() {
        \GPBMetadata\PBEnterMachine::initOnce();
        parent::__construct();
    }

    /**
     *机台ID
     *
     * Generated from protobuf field <code>int32 machineId = 1;</code>
     * @return int
     */
    public function getMachineId()
    {
        return $this->machineId;
    }

    /**
     *机台ID
     *
     * Generated from protobuf field <code>int32 machineId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMachineId($var)
    {
        GPBUtil::checkInt32($var);
        $this->machineId = $var;

        return $this;
    }

    /**
     *当前下注倍数
     *
     * Generated from protobuf field <code>int32 betMultiple = 2;</code>
     * @return int
     */
    public function getBetMultiple()
    {
        return $this->betMultiple;
    }

    /**
     *当前下注倍数
     *
     * Generated from protobuf field <code>int32 betMultiple = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBetMultiple($var)
    {
        GPBUtil::checkInt32($var);
        $this->betMultiple = $var;

        return $this;
    }

    /**
     *当前下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 3;</code>
     * @return int|string
     */
    public function getTotalBet()
    {
        return $this->totalBet;
    }

    /**
     *当前下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalBet($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalBet = $var;

        return $this;
    }

    /**
     *待恢复下注额
     *
     * Generated from protobuf field <code>int64 resumeBet = 4;</code>
     * @return int|string
     */
    public function getResumeBet()
    {
        return $this->resumeBet;
    }

    /**
     *待恢复下注额
     *
     * Generated from protobuf field <code>int64 resumeBet = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setResumeBet($var)
    {
        GPBUtil::checkInt64($var);
        $this->resumeBet = $var;

        return $this;
    }

    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 5;</code>
     * @return int|string
     */
    public function getTotalWin()
    {
        return $this->totalWin;
    }

    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalWin($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalWin = $var;

        return $this;
    }

    /**
     *用户金币余额
     *
     * Generated from protobuf field <code>int64 coins = 6;</code>
     * @return int|string
     */
    public function getCoins()
    {
        return $this->coins;
    }

    /**
     *用户金币余额
     *
     * Generated from protobuf field <code>int64 coins = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCoins($var)
    {
        GPBUtil::checkInt64($var);
        $this->coins = $var;

        return $this;
    }

    /**
     *用户gem余额
     *
     * Generated from protobuf field <code>int64 gem = 7;</code>
     * @return int|string
     */
    public function getGem()
    {
        return $this->gem;
    }

    /**
     *用户gem余额
     *
     * Generated from protobuf field <code>int64 gem = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGem($var)
    {
        GPBUtil::checkInt64($var);
        $this->gem = $var;

        return $this;
    }

    /**
     *feature信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_FeatureInfo featureInfo = 8;</code>
     * @return \GPBClass\Message\PB_FeatureInfo
     */
    public function getFeatureInfo()
    {
        return $this->featureInfo;
    }

    /**
     *feature信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_FeatureInfo featureInfo = 8;</code>
     * @param \GPBClass\Message\PB_FeatureInfo $var
     * @return $this
     */
    public function setFeatureInfo($var)
    {
        GPBUtil::checkMessage($var, \GPBClass\Message\PB_FeatureInfo::class);
        $this->featureInfo = $var;

        return $this;
    }

    /**
     *机台初始化元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getElements()
    {
        return $this->elements;
    }

    /**
     *机台初始化元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 9;</code>
     * @param \GPBClass\Message\PB_SlotsElement[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_SlotsElement::class);
        $this->elements = $arr;

        return $this;
    }

    /**
     *轴上悬浮的元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement stickyElements = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStickyElements()
    {
        return $this->stickyElements;
    }

    /**
     *轴上悬浮的元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement stickyElements = 10;</code>
     * @param \GPBClass\Message\PB_SlotsElement[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStickyElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_SlotsElement::class);
        $this->stickyElements = $arr;

        return $this;
    }

    /**
     *解锁下注倍数选项
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BetOption betOptions = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBetOptions()
    {
        return $this->betOptions;
    }

    /**
     *解锁下注倍数选项
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BetOption betOptions = 11;</code>
     * @param \GPBClass\Message\PB_BetOption[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBetOptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_BetOption::class);
        $this->betOptions = $arr;

        return $this;
    }

    /**
     *ultra下注倍数选项
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BetOption ultraBetOptions = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUltraBetOptions()
    {
        return $this->ultraBetOptions;
    }

    /**
     *ultra下注倍数选项
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BetOption ultraBetOptions = 12;</code>
     * @param \GPBClass\Message\PB_BetOption[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUltraBetOptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_BetOption::class);
        $this->ultraBetOptions = $arr;

        return $this;
    }

    /**
     *全部下注倍数选项
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BetOption allBetOptions = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllBetOptions()
    {
        return $this->allBetOptions;
    }

    /**
     *全部下注倍数选项
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BetOption allBetOptions = 13;</code>
     * @param \GPBClass\Message\PB_BetOption[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllBetOptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_BetOption::class);
        $this->allBetOptions = $arr;

        return $this;
    }

    /**
     *下次spin轴上的stack替换元素
     *
     * Generated from protobuf field <code>repeated string nextStacks = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNextStacks()
    {
        return $this->nextStacks;
    }

    /**
     *下次spin轴上的stack替换元素
     *
     * Generated from protobuf field <code>repeated string nextStacks = 14;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNextStacks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->nextStacks = $arr;

        return $this;
    }

    /**
     * 消息
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_MessageBase64List nextMessages = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNextMessages()
    {
        return $this->nextMessages;
    }

    /**
     * 消息
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_MessageBase64List nextMessages = 15;</code>
     * @param \GPBClass\Message\PB_MessageBase64List[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNextMessages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_MessageBase64List::class);
        $this->nextMessages = $arr;

        return $this;
    }

}

