<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_EnterMachine.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_EnterMachine_Req</code>
 */
class PB_EnterMachine_Req extends \Google\Protobuf\Internal\Message
{
    /**
     *机台ID
     *
     * Generated from protobuf field <code>int32 machineId = 1;</code>
     */
    private $machineId = 0;

    public function __construct() {
        \GPBMetadata\PBEnterMachine::initOnce();
        parent::__construct();
    }

    /**
     *机台ID
     *
     * Generated from protobuf field <code>int32 machineId = 1;</code>
     * @return int
     */
    public function getMachineId()
    {
        return $this->machineId;
    }

    /**
     *机台ID
     *
     * Generated from protobuf field <code>int32 machineId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMachineId($var)
    {
        GPBUtil::checkInt32($var);
        $this->machineId = $var;

        return $this;
    }

}

