<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_ExitMachine.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_ExitMachine_Req</code>
 */
class PB_ExitMachine_Req extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\PBExitMachine::initOnce();
        parent::__construct();
    }

}

