<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_FetchWheeItems.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_FetchWheeItemInfo</code>
 */
class PB_FetchWheeItemInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string item = 1;</code>
     */
    private $item = '';
    /**
     * Generated from protobuf field <code>int32 pos = 2;</code>
     */
    private $pos = 0;
    /**
     * Generated from protobuf field <code>string value = 3;</code>
     */
    private $value = '';
    /**
     * Generated from protobuf field <code>int32 weight = 4;</code>
     */
    private $weight = 0;

    public function __construct() {
        \GPBMetadata\PBFetchWheeItems::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string item = 1;</code>
     * @return string
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * Generated from protobuf field <code>string item = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setItem($var)
    {
        GPBUtil::checkString($var, True);
        $this->item = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pos = 2;</code>
     * @return int
     */
    public function getPos()
    {
        return $this->pos;
    }

    /**
     * Generated from protobuf field <code>int32 pos = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPos($var)
    {
        GPBUtil::checkInt32($var);
        $this->pos = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 3;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 weight = 4;</code>
     * @return int
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>int32 weight = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setWeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->weight = $var;

        return $this;
    }

}

