<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SlotsPrize.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_FeatureElements</code>
 */
class PB_FeatureElements extends \Google\Protobuf\Internal\Message
{
    /**
     *featureId
     *
     * Generated from protobuf field <code>string featureId = 1;</code>
     */
    private $featureId = '';
    /**
     *特殊元素奖励
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 2;</code>
     */
    private $elements;

    public function __construct() {
        \GPBMetadata\PBSlotsPrize::initOnce();
        parent::__construct();
    }

    /**
     *featureId
     *
     * Generated from protobuf field <code>string featureId = 1;</code>
     * @return string
     */
    public function getFeatureId()
    {
        return $this->featureId;
    }

    /**
     *featureId
     *
     * Generated from protobuf field <code>string featureId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFeatureId($var)
    {
        GPBUtil::checkString($var, True);
        $this->featureId = $var;

        return $this;
    }

    /**
     *特殊元素奖励
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getElements()
    {
        return $this->elements;
    }

    /**
     *特殊元素奖励
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 2;</code>
     * @param \GPBClass\Message\PB_SlotsElement[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_SlotsElement::class);
        $this->elements = $arr;

        return $this;
    }

}

