<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_FetchWheeItems.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_FetchWheeItems_Req</code>
 */
class PB_FetchWheeItems_Req extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string wheelId = 1;</code>
     */
    private $wheelId = '';

    public function __construct() {
        \GPBMetadata\PBFetchWheeItems::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string wheelId = 1;</code>
     * @return string
     */
    public function getWheelId()
    {
        return $this->wheelId;
    }

    /**
     * Generated from protobuf field <code>string wheelId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWheelId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wheelId = $var;

        return $this;
    }

}

