<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_FetchWheeItems.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_FetchWheeItems_Res</code>
 */
class PB_FetchWheeItems_Res extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_FetchWheeItemInfo list = 1;</code>
     */
    private $list;

    public function __construct() {
        \GPBMetadata\PBFetchWheeItems::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_FetchWheeItemInfo list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_FetchWheeItemInfo list = 1;</code>
     * @param \GPBClass\Message\PB_FetchWheeItemInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_FetchWheeItemInfo::class);
        $this->list = $arr;

        return $this;
    }

}

