<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_FeaturesOver.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_FeaturesOver_Res</code>
 */
class PB_FeaturesOver_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 1;</code>
     */
    private $totalWin = 0;
    /**
     *所有feature赢的多少钱
     *
     * Generated from protobuf field <code>int64 featureWin = 2;</code>
     */
    private $featureWin = 0;
    /**
     *feature奖励
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_FeaturePrize featuresPrize = 3;</code>
     */
    private $featuresPrize;
    /**
     * Generated from protobuf field <code>int32 winType = 4;</code>
     */
    private $winType = 0;
    /**
     * Generated from protobuf field <code>bool settled = 5;</code>
     */
    private $settled = false;

    public function __construct() {
        \GPBMetadata\PBFeaturesOver::initOnce();
        parent::__construct();
    }

    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 1;</code>
     * @return int|string
     */
    public function getTotalWin()
    {
        return $this->totalWin;
    }

    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalWin($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalWin = $var;

        return $this;
    }

    /**
     *所有feature赢的多少钱
     *
     * Generated from protobuf field <code>int64 featureWin = 2;</code>
     * @return int|string
     */
    public function getFeatureWin()
    {
        return $this->featureWin;
    }

    /**
     *所有feature赢的多少钱
     *
     * Generated from protobuf field <code>int64 featureWin = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFeatureWin($var)
    {
        GPBUtil::checkInt64($var);
        $this->featureWin = $var;

        return $this;
    }

    /**
     *feature奖励
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_FeaturePrize featuresPrize = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFeaturesPrize()
    {
        return $this->featuresPrize;
    }

    /**
     *feature奖励
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_FeaturePrize featuresPrize = 3;</code>
     * @param \GPBClass\Message\PB_FeaturePrize[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFeaturesPrize($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_FeaturePrize::class);
        $this->featuresPrize = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 winType = 4;</code>
     * @return int
     */
    public function getWinType()
    {
        return $this->winType;
    }

    /**
     * Generated from protobuf field <code>int32 winType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setWinType($var)
    {
        GPBUtil::checkInt32($var);
        $this->winType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool settled = 5;</code>
     * @return bool
     */
    public function getSettled()
    {
        return $this->settled;
    }

    /**
     * Generated from protobuf field <code>bool settled = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setSettled($var)
    {
        GPBUtil::checkBool($var);
        $this->settled = $var;

        return $this;
    }

}

