<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_FeatureWinInfo.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_FeatureWinInfo</code>
 */
class PB_FeatureWinInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *本次feature总赢得金币数
     *
     * Generated from protobuf field <code>int64 featureWin = 1;</code>
     */
    private $featureWin = 0;
    /**
     *本次spin当前总赢得金币数(包含paylineWin+featureWin)
     *
     * Generated from protobuf field <code>int64 coinsWin = 2;</code>
     */
    private $coinsWin = 0;
    /**
     *当前总的totalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 3;</code>
     */
    private $totalWin = 0;
    /**
     *大奖类型(spinEnd=true时有值)
     *
     * Generated from protobuf field <code>int32 winType = 4;</code>
     */
    private $winType = 0;
    /**
     *广告加成倍数
     *
     * Generated from protobuf field <code>int32 adMultiple = 5;</code>
     */
    private $adMultiple = 0;
    /**
     *本次spin是否结束
     *
     * Generated from protobuf field <code>bool spinEnd = 6;</code>
     */
    private $spinEnd = false;
    /**
     *是否结算
     *
     * Generated from protobuf field <code>bool settled = 7;</code>
     */
    private $settled = false;

    public function __construct() {
        \GPBMetadata\PBFeatureWinInfo::initOnce();
        parent::__construct();
    }

    /**
     *本次feature总赢得金币数
     *
     * Generated from protobuf field <code>int64 featureWin = 1;</code>
     * @return int|string
     */
    public function getFeatureWin()
    {
        return $this->featureWin;
    }

    /**
     *本次feature总赢得金币数
     *
     * Generated from protobuf field <code>int64 featureWin = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFeatureWin($var)
    {
        GPBUtil::checkInt64($var);
        $this->featureWin = $var;

        return $this;
    }

    /**
     *本次spin当前总赢得金币数(包含paylineWin+featureWin)
     *
     * Generated from protobuf field <code>int64 coinsWin = 2;</code>
     * @return int|string
     */
    public function getCoinsWin()
    {
        return $this->coinsWin;
    }

    /**
     *本次spin当前总赢得金币数(包含paylineWin+featureWin)
     *
     * Generated from protobuf field <code>int64 coinsWin = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCoinsWin($var)
    {
        GPBUtil::checkInt64($var);
        $this->coinsWin = $var;

        return $this;
    }

    /**
     *当前总的totalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 3;</code>
     * @return int|string
     */
    public function getTotalWin()
    {
        return $this->totalWin;
    }

    /**
     *当前总的totalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalWin($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalWin = $var;

        return $this;
    }

    /**
     *大奖类型(spinEnd=true时有值)
     *
     * Generated from protobuf field <code>int32 winType = 4;</code>
     * @return int
     */
    public function getWinType()
    {
        return $this->winType;
    }

    /**
     *大奖类型(spinEnd=true时有值)
     *
     * Generated from protobuf field <code>int32 winType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setWinType($var)
    {
        GPBUtil::checkInt32($var);
        $this->winType = $var;

        return $this;
    }

    /**
     *广告加成倍数
     *
     * Generated from protobuf field <code>int32 adMultiple = 5;</code>
     * @return int
     */
    public function getAdMultiple()
    {
        return $this->adMultiple;
    }

    /**
     *广告加成倍数
     *
     * Generated from protobuf field <code>int32 adMultiple = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAdMultiple($var)
    {
        GPBUtil::checkInt32($var);
        $this->adMultiple = $var;

        return $this;
    }

    /**
     *本次spin是否结束
     *
     * Generated from protobuf field <code>bool spinEnd = 6;</code>
     * @return bool
     */
    public function getSpinEnd()
    {
        return $this->spinEnd;
    }

    /**
     *本次spin是否结束
     *
     * Generated from protobuf field <code>bool spinEnd = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setSpinEnd($var)
    {
        GPBUtil::checkBool($var);
        $this->spinEnd = $var;

        return $this;
    }

    /**
     *是否结算
     *
     * Generated from protobuf field <code>bool settled = 7;</code>
     * @return bool
     */
    public function getSettled()
    {
        return $this->settled;
    }

    /**
     *是否结算
     *
     * Generated from protobuf field <code>bool settled = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setSettled($var)
    {
        GPBUtil::checkBool($var);
        $this->settled = $var;

        return $this;
    }

}

