<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_EnterMachine.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_FeatureInfo</code>
 */
class PB_FeatureInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *当前featureId
     *
     * Generated from protobuf field <code>string featureId = 1;</code>
     */
    private $featureId = '';
    /**
     *feature回退列表
     *
     * Generated from protobuf field <code>repeated string bakFeatures = 2;</code>
     */
    private $bakFeatures;

    public function __construct() {
        \GPBMetadata\PBEnterMachine::initOnce();
        parent::__construct();
    }

    /**
     *当前featureId
     *
     * Generated from protobuf field <code>string featureId = 1;</code>
     * @return string
     */
    public function getFeatureId()
    {
        return $this->featureId;
    }

    /**
     *当前featureId
     *
     * Generated from protobuf field <code>string featureId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFeatureId($var)
    {
        GPBUtil::checkString($var, True);
        $this->featureId = $var;

        return $this;
    }

    /**
     *feature回退列表
     *
     * Generated from protobuf field <code>repeated string bakFeatures = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBakFeatures()
    {
        return $this->bakFeatures;
    }

    /**
     *feature回退列表
     *
     * Generated from protobuf field <code>repeated string bakFeatures = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBakFeatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->bakFeatures = $arr;

        return $this;
    }

}

