<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_FeaturesOver.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_FeaturePrize</code>
 */
class PB_FeaturePrize extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string featureId = 1;</code>
     */
    private $featureId = '';
    /**
     * Generated from protobuf field <code>int64 coinsWin = 2;</code>
     */
    private $coinsWin = 0;

    public function __construct() {
        \GPBMetadata\PBFeaturesOver::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string featureId = 1;</code>
     * @return string
     */
    public function getFeatureId()
    {
        return $this->featureId;
    }

    /**
     * Generated from protobuf field <code>string featureId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFeatureId($var)
    {
        GPBUtil::checkString($var, True);
        $this->featureId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 coinsWin = 2;</code>
     * @return int|string
     */
    public function getCoinsWin()
    {
        return $this->coinsWin;
    }

    /**
     * Generated from protobuf field <code>int64 coinsWin = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCoinsWin($var)
    {
        GPBUtil::checkInt64($var);
        $this->coinsWin = $var;

        return $this;
    }

}

