<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_HoldAndSpin.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_HoldAndSpin_Res</code>
 */
class PB_HoldAndSpin_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *命中的元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 1;</code>
     */
    private $elements;
    /**
     *feature是否结束
     *
     * Generated from protobuf field <code>bool isOver = 2;</code>
     */
    private $isOver = false;
    /**
     *feature结束时所有bonus总赢得
     *
     * Generated from protobuf field <code>int64 bonusWin = 3;</code>
     */
    private $bonusWin = 0;
    /**
     *本次feature获得的jackpot奖励
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_JackpotPrize jackpotPrizes = 4;</code>
     */
    private $jackpotPrizes;
    /**
     *剩余次数
     *
     * Generated from protobuf field <code>int32 times = 5;</code>
     */
    private $times = 0;
    /**
     *收集总个数
     *
     * Generated from protobuf field <code>int32 collected = 6;</code>
     */
    private $collected = 0;
    /**
     *feature赢钱信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_FeatureWinInfo winInfo = 7;</code>
     */
    private $winInfo = null;

    public function __construct() {
        \GPBMetadata\PBHoldAndSpin::initOnce();
        parent::__construct();
    }

    /**
     *命中的元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getElements()
    {
        return $this->elements;
    }

    /**
     *命中的元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 1;</code>
     * @param \GPBClass\Message\PB_SlotsElement[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_SlotsElement::class);
        $this->elements = $arr;

        return $this;
    }

    /**
     *feature是否结束
     *
     * Generated from protobuf field <code>bool isOver = 2;</code>
     * @return bool
     */
    public function getIsOver()
    {
        return $this->isOver;
    }

    /**
     *feature是否结束
     *
     * Generated from protobuf field <code>bool isOver = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsOver($var)
    {
        GPBUtil::checkBool($var);
        $this->isOver = $var;

        return $this;
    }

    /**
     *feature结束时所有bonus总赢得
     *
     * Generated from protobuf field <code>int64 bonusWin = 3;</code>
     * @return int|string
     */
    public function getBonusWin()
    {
        return $this->bonusWin;
    }

    /**
     *feature结束时所有bonus总赢得
     *
     * Generated from protobuf field <code>int64 bonusWin = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBonusWin($var)
    {
        GPBUtil::checkInt64($var);
        $this->bonusWin = $var;

        return $this;
    }

    /**
     *本次feature获得的jackpot奖励
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_JackpotPrize jackpotPrizes = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJackpotPrizes()
    {
        return $this->jackpotPrizes;
    }

    /**
     *本次feature获得的jackpot奖励
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_JackpotPrize jackpotPrizes = 4;</code>
     * @param \GPBClass\Message\PB_JackpotPrize[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJackpotPrizes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_JackpotPrize::class);
        $this->jackpotPrizes = $arr;

        return $this;
    }

    /**
     *剩余次数
     *
     * Generated from protobuf field <code>int32 times = 5;</code>
     * @return int
     */
    public function getTimes()
    {
        return $this->times;
    }

    /**
     *剩余次数
     *
     * Generated from protobuf field <code>int32 times = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setTimes($var)
    {
        GPBUtil::checkInt32($var);
        $this->times = $var;

        return $this;
    }

    /**
     *收集总个数
     *
     * Generated from protobuf field <code>int32 collected = 6;</code>
     * @return int
     */
    public function getCollected()
    {
        return $this->collected;
    }

    /**
     *收集总个数
     *
     * Generated from protobuf field <code>int32 collected = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setCollected($var)
    {
        GPBUtil::checkInt32($var);
        $this->collected = $var;

        return $this;
    }

    /**
     *feature赢钱信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_FeatureWinInfo winInfo = 7;</code>
     * @return \GPBClass\Message\PB_FeatureWinInfo
     */
    public function getWinInfo()
    {
        return $this->winInfo;
    }

    /**
     *feature赢钱信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_FeatureWinInfo winInfo = 7;</code>
     * @param \GPBClass\Message\PB_FeatureWinInfo $var
     * @return $this
     */
    public function setWinInfo($var)
    {
        GPBUtil::checkMessage($var, \GPBClass\Message\PB_FeatureWinInfo::class);
        $this->winInfo = $var;

        return $this;
    }

}

