<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_InitCollect.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_InitCollect_Res</code>
 */
class PB_InitCollect_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *当前收集信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_CollectInfo collectInfo = 1;</code>
     */
    private $collectInfo = null;

    public function __construct() {
        \GPBMetadata\PBInitCollect::initOnce();
        parent::__construct();
    }

    /**
     *当前收集信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_CollectInfo collectInfo = 1;</code>
     * @return \GPBClass\Message\PB_CollectInfo
     */
    public function getCollectInfo()
    {
        return $this->collectInfo;
    }

    /**
     *当前收集信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_CollectInfo collectInfo = 1;</code>
     * @param \GPBClass\Message\PB_CollectInfo $var
     * @return $this
     */
    public function setCollectInfo($var)
    {
        GPBUtil::checkMessage($var, \GPBClass\Message\PB_CollectInfo::class);
        $this->collectInfo = $var;

        return $this;
    }

}

