<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_ItemInfo.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_ItemInfo</code>
 */
class PB_ItemInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *道具ID
     *
     * Generated from protobuf field <code>string itemId = 1;</code>
     */
    private $itemId = '';
    /**
     *道具类型
     *
     * Generated from protobuf field <code>int32 type = 2;</code>
     */
    private $type = 0;
    /**
     *道具数量
     *
     * Generated from protobuf field <code>int32 count = 3;</code>
     */
    private $count = 0;
    /**
     *物品附加值
     *
     * Generated from protobuf field <code>string value = 4;</code>
     */
    private $value = '';
    /**
     *BUFF物品有效时长
     *
     * Generated from protobuf field <code>int64 duration = 5;</code>
     */
    private $duration = 0;

    public function __construct() {
        \GPBMetadata\PBItemInfo::initOnce();
        parent::__construct();
    }

    /**
     *道具ID
     *
     * Generated from protobuf field <code>string itemId = 1;</code>
     * @return string
     */
    public function getItemId()
    {
        return $this->itemId;
    }

    /**
     *道具ID
     *
     * Generated from protobuf field <code>string itemId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setItemId($var)
    {
        GPBUtil::checkString($var, True);
        $this->itemId = $var;

        return $this;
    }

    /**
     *道具类型
     *
     * Generated from protobuf field <code>int32 type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *道具类型
     *
     * Generated from protobuf field <code>int32 type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     *道具数量
     *
     * Generated from protobuf field <code>int32 count = 3;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     *道具数量
     *
     * Generated from protobuf field <code>int32 count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->count = $var;

        return $this;
    }

    /**
     *物品附加值
     *
     * Generated from protobuf field <code>string value = 4;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     *物品附加值
     *
     * Generated from protobuf field <code>string value = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     *BUFF物品有效时长
     *
     * Generated from protobuf field <code>int64 duration = 5;</code>
     * @return int|string
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     *BUFF物品有效时长
     *
     * Generated from protobuf field <code>int64 duration = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkInt64($var);
        $this->duration = $var;

        return $this;
    }

}

