<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_JackpotPickGame.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_JackpotPickGame_Req</code>
 */
class PB_JackpotPickGame_Req extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\PBJackpotPickGame::initOnce();
        parent::__construct();
    }

}

