<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_JackpotPrize.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_JackpotPrize</code>
 */
class PB_JackpotPrize extends \Google\Protobuf\Internal\Message
{
    /**
     *jackpotId
     *
     * Generated from protobuf field <code>string jackpotId = 1;</code>
     */
    private $jackpotId = '';
    /**
     *jackpotName
     *
     * Generated from protobuf field <code>string jackpotName = 2;</code>
     */
    private $jackpotName = '';
    /**
     *jackpot奖励
     *
     * Generated from protobuf field <code>double coins = 3;</code>
     */
    private $coins = 0.0;

    public function __construct() {
        \GPBMetadata\PBJackpotPrize::initOnce();
        parent::__construct();
    }

    /**
     *jackpotId
     *
     * Generated from protobuf field <code>string jackpotId = 1;</code>
     * @return string
     */
    public function getJackpotId()
    {
        return $this->jackpotId;
    }

    /**
     *jackpotId
     *
     * Generated from protobuf field <code>string jackpotId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJackpotId($var)
    {
        GPBUtil::checkString($var, True);
        $this->jackpotId = $var;

        return $this;
    }

    /**
     *jackpotName
     *
     * Generated from protobuf field <code>string jackpotName = 2;</code>
     * @return string
     */
    public function getJackpotName()
    {
        return $this->jackpotName;
    }

    /**
     *jackpotName
     *
     * Generated from protobuf field <code>string jackpotName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setJackpotName($var)
    {
        GPBUtil::checkString($var, True);
        $this->jackpotName = $var;

        return $this;
    }

    /**
     *jackpot奖励
     *
     * Generated from protobuf field <code>double coins = 3;</code>
     * @return float
     */
    public function getCoins()
    {
        return $this->coins;
    }

    /**
     *jackpot奖励
     *
     * Generated from protobuf field <code>double coins = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setCoins($var)
    {
        GPBUtil::checkDouble($var);
        $this->coins = $var;

        return $this;
    }

}

