<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_JackpotInfo.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_JackpotInfo</code>
 */
class PB_JackpotInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *jackpotId
     *
     * Generated from protobuf field <code>string jackpotId = 1;</code>
     */
    private $jackpotId = '';
    /**
     *jackpotName
     *
     * Generated from protobuf field <code>string jackpotName = 2;</code>
     */
    private $jackpotName = '';
    /**
     *激活所需最小下注挡位
     *
     * Generated from protobuf field <code>int32 minBetLevel = 3;</code>
     */
    private $minBetLevel = 0;
    /**
     *激活所需最大下注挡位，0为不限制
     *
     * Generated from protobuf field <code>int32 maxBetLevel = 4;</code>
     */
    private $maxBetLevel = 0;
    /**
     *奖池金额是否受下注额影响
     *
     * Generated from protobuf field <code>bool awardByBet = 5;</code>
     */
    private $awardByBet = false;
    /**
     *奖池初始值
     *
     * Generated from protobuf field <code>double awardBegin = 6;</code>
     */
    private $awardBegin = 0.0;
    /**
     *奖池最大值
     *
     * Generated from protobuf field <code>double awardEnd = 7;</code>
     */
    private $awardEnd = 0.0;
    /**
     *奖池周期(秒数)
     *
     * Generated from protobuf field <code>int64 duration = 8;</code>
     */
    private $duration = 0;
    /**
     *奖池周期内增长倍数
     *
     * Generated from protobuf field <code>double growthMultiple = 9;</code>
     */
    private $growthMultiple = 0.0;
    /**
     *奖池创建时间(时间戳)
     *
     * Generated from protobuf field <code>int64 createTime = 10;</code>
     */
    private $createTime = 0;
    /**
     *达成领奖所需总进度
     *
     * Generated from protobuf field <code>int32 target = 11;</code>
     */
    private $target = 0;
    /**
     *已获得进度
     *
     * Generated from protobuf field <code>int32 progress = 12;</code>
     */
    private $progress = 0;
    /**
     *是否已解锁
     *
     * Generated from protobuf field <code>bool unlocked = 13;</code>
     */
    private $unlocked = false;

    public function __construct() {
        \GPBMetadata\PBJackpotInfo::initOnce();
        parent::__construct();
    }

    /**
     *jackpotId
     *
     * Generated from protobuf field <code>string jackpotId = 1;</code>
     * @return string
     */
    public function getJackpotId()
    {
        return $this->jackpotId;
    }

    /**
     *jackpotId
     *
     * Generated from protobuf field <code>string jackpotId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setJackpotId($var)
    {
        GPBUtil::checkString($var, True);
        $this->jackpotId = $var;

        return $this;
    }

    /**
     *jackpotName
     *
     * Generated from protobuf field <code>string jackpotName = 2;</code>
     * @return string
     */
    public function getJackpotName()
    {
        return $this->jackpotName;
    }

    /**
     *jackpotName
     *
     * Generated from protobuf field <code>string jackpotName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setJackpotName($var)
    {
        GPBUtil::checkString($var, True);
        $this->jackpotName = $var;

        return $this;
    }

    /**
     *激活所需最小下注挡位
     *
     * Generated from protobuf field <code>int32 minBetLevel = 3;</code>
     * @return int
     */
    public function getMinBetLevel()
    {
        return $this->minBetLevel;
    }

    /**
     *激活所需最小下注挡位
     *
     * Generated from protobuf field <code>int32 minBetLevel = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMinBetLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->minBetLevel = $var;

        return $this;
    }

    /**
     *激活所需最大下注挡位，0为不限制
     *
     * Generated from protobuf field <code>int32 maxBetLevel = 4;</code>
     * @return int
     */
    public function getMaxBetLevel()
    {
        return $this->maxBetLevel;
    }

    /**
     *激活所需最大下注挡位，0为不限制
     *
     * Generated from protobuf field <code>int32 maxBetLevel = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxBetLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->maxBetLevel = $var;

        return $this;
    }

    /**
     *奖池金额是否受下注额影响
     *
     * Generated from protobuf field <code>bool awardByBet = 5;</code>
     * @return bool
     */
    public function getAwardByBet()
    {
        return $this->awardByBet;
    }

    /**
     *奖池金额是否受下注额影响
     *
     * Generated from protobuf field <code>bool awardByBet = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setAwardByBet($var)
    {
        GPBUtil::checkBool($var);
        $this->awardByBet = $var;

        return $this;
    }

    /**
     *奖池初始值
     *
     * Generated from protobuf field <code>double awardBegin = 6;</code>
     * @return float
     */
    public function getAwardBegin()
    {
        return $this->awardBegin;
    }

    /**
     *奖池初始值
     *
     * Generated from protobuf field <code>double awardBegin = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setAwardBegin($var)
    {
        GPBUtil::checkDouble($var);
        $this->awardBegin = $var;

        return $this;
    }

    /**
     *奖池最大值
     *
     * Generated from protobuf field <code>double awardEnd = 7;</code>
     * @return float
     */
    public function getAwardEnd()
    {
        return $this->awardEnd;
    }

    /**
     *奖池最大值
     *
     * Generated from protobuf field <code>double awardEnd = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setAwardEnd($var)
    {
        GPBUtil::checkDouble($var);
        $this->awardEnd = $var;

        return $this;
    }

    /**
     *奖池周期(秒数)
     *
     * Generated from protobuf field <code>int64 duration = 8;</code>
     * @return int|string
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     *奖池周期(秒数)
     *
     * Generated from protobuf field <code>int64 duration = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkInt64($var);
        $this->duration = $var;

        return $this;
    }

    /**
     *奖池周期内增长倍数
     *
     * Generated from protobuf field <code>double growthMultiple = 9;</code>
     * @return float
     */
    public function getGrowthMultiple()
    {
        return $this->growthMultiple;
    }

    /**
     *奖池周期内增长倍数
     *
     * Generated from protobuf field <code>double growthMultiple = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setGrowthMultiple($var)
    {
        GPBUtil::checkDouble($var);
        $this->growthMultiple = $var;

        return $this;
    }

    /**
     *奖池创建时间(时间戳)
     *
     * Generated from protobuf field <code>int64 createTime = 10;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->createTime;
    }

    /**
     *奖池创建时间(时间戳)
     *
     * Generated from protobuf field <code>int64 createTime = 10;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->createTime = $var;

        return $this;
    }

    /**
     *达成领奖所需总进度
     *
     * Generated from protobuf field <code>int32 target = 11;</code>
     * @return int
     */
    public function getTarget()
    {
        return $this->target;
    }

    /**
     *达成领奖所需总进度
     *
     * Generated from protobuf field <code>int32 target = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setTarget($var)
    {
        GPBUtil::checkInt32($var);
        $this->target = $var;

        return $this;
    }

    /**
     *已获得进度
     *
     * Generated from protobuf field <code>int32 progress = 12;</code>
     * @return int
     */
    public function getProgress()
    {
        return $this->progress;
    }

    /**
     *已获得进度
     *
     * Generated from protobuf field <code>int32 progress = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setProgress($var)
    {
        GPBUtil::checkInt32($var);
        $this->progress = $var;

        return $this;
    }

    /**
     *是否已解锁
     *
     * Generated from protobuf field <code>bool unlocked = 13;</code>
     * @return bool
     */
    public function getUnlocked()
    {
        return $this->unlocked;
    }

    /**
     *是否已解锁
     *
     * Generated from protobuf field <code>bool unlocked = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setUnlocked($var)
    {
        GPBUtil::checkBool($var);
        $this->unlocked = $var;

        return $this;
    }

}

