<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_JackpotPickGame.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_JackpotPickGame_Res</code>
 */
class PB_JackpotPickGame_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *结算信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_FeatureWinInfo winInfo = 1;</code>
     */
    private $winInfo = null;
    /**
     * pick的结果
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_JackpotPickResult pickResult = 2;</code>
     */
    private $pickResult = null;
    /**
     *命中的jackpot的奖励信息
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_JackpotPrize jackpotPrizes = 3;</code>
     */
    private $jackpotPrizes;

    public function __construct() {
        \GPBMetadata\PBJackpotPickGame::initOnce();
        parent::__construct();
    }

    /**
     *结算信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_FeatureWinInfo winInfo = 1;</code>
     * @return \GPBClass\Message\PB_FeatureWinInfo
     */
    public function getWinInfo()
    {
        return $this->winInfo;
    }

    /**
     *结算信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_FeatureWinInfo winInfo = 1;</code>
     * @param \GPBClass\Message\PB_FeatureWinInfo $var
     * @return $this
     */
    public function setWinInfo($var)
    {
        GPBUtil::checkMessage($var, \GPBClass\Message\PB_FeatureWinInfo::class);
        $this->winInfo = $var;

        return $this;
    }

    /**
     * pick的结果
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_JackpotPickResult pickResult = 2;</code>
     * @return \GPBClass\Message\PB_JackpotPickResult
     */
    public function getPickResult()
    {
        return $this->pickResult;
    }

    /**
     * pick的结果
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_JackpotPickResult pickResult = 2;</code>
     * @param \GPBClass\Message\PB_JackpotPickResult $var
     * @return $this
     */
    public function setPickResult($var)
    {
        GPBUtil::checkMessage($var, \GPBClass\Message\PB_JackpotPickResult::class);
        $this->pickResult = $var;

        return $this;
    }

    /**
     *命中的jackpot的奖励信息
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_JackpotPrize jackpotPrizes = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJackpotPrizes()
    {
        return $this->jackpotPrizes;
    }

    /**
     *命中的jackpot的奖励信息
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_JackpotPrize jackpotPrizes = 3;</code>
     * @param \GPBClass\Message\PB_JackpotPrize[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJackpotPrizes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_JackpotPrize::class);
        $this->jackpotPrizes = $arr;

        return $this;
    }

}

