<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_JackpotPickGame.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_JackpotPickResult</code>
 */
class PB_JackpotPickResult extends \Google\Protobuf\Internal\Message
{
    /**
     *命中的jackpot
     *
     * Generated from protobuf field <code>repeated string hitJackPots = 1;</code>
     */
    private $hitJackPots;
    /**
     *pick的卡片
     *
     * Generated from protobuf field <code>repeated string pickCards = 2;</code>
     */
    private $pickCards;
    /**
     *pick多少次
     *
     * Generated from protobuf field <code>int32 pickTimes = 3;</code>
     */
    private $pickTimes = 0;

    public function __construct() {
        \GPBMetadata\PBJackpotPickGame::initOnce();
        parent::__construct();
    }

    /**
     *命中的jackpot
     *
     * Generated from protobuf field <code>repeated string hitJackPots = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHitJackPots()
    {
        return $this->hitJackPots;
    }

    /**
     *命中的jackpot
     *
     * Generated from protobuf field <code>repeated string hitJackPots = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHitJackPots($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->hitJackPots = $arr;

        return $this;
    }

    /**
     *pick的卡片
     *
     * Generated from protobuf field <code>repeated string pickCards = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPickCards()
    {
        return $this->pickCards;
    }

    /**
     *pick的卡片
     *
     * Generated from protobuf field <code>repeated string pickCards = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPickCards($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->pickCards = $arr;

        return $this;
    }

    /**
     *pick多少次
     *
     * Generated from protobuf field <code>int32 pickTimes = 3;</code>
     * @return int
     */
    public function getPickTimes()
    {
        return $this->pickTimes;
    }

    /**
     *pick多少次
     *
     * Generated from protobuf field <code>int32 pickTimes = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPickTimes($var)
    {
        GPBUtil::checkInt32($var);
        $this->pickTimes = $var;

        return $this;
    }

}

