<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_MessageBase64List.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_MessageBase64List</code>
 */
class PB_MessageBase64List extends \Google\Protobuf\Internal\Message
{
    /**
     * 消息ID
     *
     * Generated from protobuf field <code>int32 msgId = 1;</code>
     */
    private $msgId = 0;
    /**
     * 消息 base64 MSG
     *
     * Generated from protobuf field <code>string msgBase64 = 2;</code>
     */
    private $msgBase64 = '';

    public function __construct() {
        \GPBMetadata\PBMessageBase64List::initOnce();
        parent::__construct();
    }

    /**
     * 消息ID
     *
     * Generated from protobuf field <code>int32 msgId = 1;</code>
     * @return int
     */
    public function getMsgId()
    {
        return $this->msgId;
    }

    /**
     * 消息ID
     *
     * Generated from protobuf field <code>int32 msgId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMsgId($var)
    {
        GPBUtil::checkInt32($var);
        $this->msgId = $var;

        return $this;
    }

    /**
     * 消息 base64 MSG
     *
     * Generated from protobuf field <code>string msgBase64 = 2;</code>
     * @return string
     */
    public function getMsgBase64()
    {
        return $this->msgBase64;
    }

    /**
     * 消息 base64 MSG
     *
     * Generated from protobuf field <code>string msgBase64 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsgBase64($var)
    {
        GPBUtil::checkString($var, True);
        $this->msgBase64 = $var;

        return $this;
    }

}

