<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_NTF_CollectProgress.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_NTF_CollectProgress_Res</code>
 */
class PB_NTF_CollectProgress_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *当前总进度
     *
     * Generated from protobuf field <code>int64 collectProgress = 1;</code>
     */
    private $collectProgress = 0;
    /**
     *当前平均bet
     *
     * Generated from protobuf field <code>int64 collectAvgBet = 2;</code>
     */
    private $collectAvgBet = 0;
    /**
     *当前收集值
     *
     * Generated from protobuf field <code>int64 collectValue = 3;</code>
     */
    private $collectValue = 0;

    public function __construct() {
        \GPBMetadata\PBNTFCollectProgress::initOnce();
        parent::__construct();
    }

    /**
     *当前总进度
     *
     * Generated from protobuf field <code>int64 collectProgress = 1;</code>
     * @return int|string
     */
    public function getCollectProgress()
    {
        return $this->collectProgress;
    }

    /**
     *当前总进度
     *
     * Generated from protobuf field <code>int64 collectProgress = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectProgress($var)
    {
        GPBUtil::checkInt64($var);
        $this->collectProgress = $var;

        return $this;
    }

    /**
     *当前平均bet
     *
     * Generated from protobuf field <code>int64 collectAvgBet = 2;</code>
     * @return int|string
     */
    public function getCollectAvgBet()
    {
        return $this->collectAvgBet;
    }

    /**
     *当前平均bet
     *
     * Generated from protobuf field <code>int64 collectAvgBet = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectAvgBet($var)
    {
        GPBUtil::checkInt64($var);
        $this->collectAvgBet = $var;

        return $this;
    }

    /**
     *当前收集值
     *
     * Generated from protobuf field <code>int64 collectValue = 3;</code>
     * @return int|string
     */
    public function getCollectValue()
    {
        return $this->collectValue;
    }

    /**
     *当前收集值
     *
     * Generated from protobuf field <code>int64 collectValue = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCollectValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->collectValue = $var;

        return $this;
    }

}

