<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_NTF_JackpotPrize.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_NTF_JackpotPrize_Res</code>
 */
class PB_NTF_JackpotPrize_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *jackpot奖励列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_JackpotPrize jackpotPrizes = 1;</code>
     */
    private $jackpotPrizes;

    public function __construct() {
        \GPBMetadata\PBNTFJackpotPrize::initOnce();
        parent::__construct();
    }

    /**
     *jackpot奖励列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_JackpotPrize jackpotPrizes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJackpotPrizes()
    {
        return $this->jackpotPrizes;
    }

    /**
     *jackpot奖励列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_JackpotPrize jackpotPrizes = 1;</code>
     * @param \GPBClass\Message\PB_JackpotPrize[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJackpotPrizes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_JackpotPrize::class);
        $this->jackpotPrizes = $arr;

        return $this;
    }

}

