<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_NTF_LevelPrize.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_NTF_LevelPrize_Res</code>
 */
class PB_NTF_LevelPrize_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *当前经验值
     *
     * Generated from protobuf field <code>int64 exp = 1;</code>
     */
    private $exp = 0;
    /**
     *当前等级
     *
     * Generated from protobuf field <code>int32 level = 2;</code>
     */
    private $level = 0;
    /**
     *是否升级
     *
     * Generated from protobuf field <code>bool levelUp = 3;</code>
     */
    private $levelUp = false;
    /**
     *奖励列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_PrizeInfo prizes = 4;</code>
     */
    private $prizes;
    /**
     *下注倍数选项，升级导致变动
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BetOption betOptions = 5;</code>
     */
    private $betOptions;

    public function __construct() {
        \GPBMetadata\PBNTFLevelPrize::initOnce();
        parent::__construct();
    }

    /**
     *当前经验值
     *
     * Generated from protobuf field <code>int64 exp = 1;</code>
     * @return int|string
     */
    public function getExp()
    {
        return $this->exp;
    }

    /**
     *当前经验值
     *
     * Generated from protobuf field <code>int64 exp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExp($var)
    {
        GPBUtil::checkInt64($var);
        $this->exp = $var;

        return $this;
    }

    /**
     *当前等级
     *
     * Generated from protobuf field <code>int32 level = 2;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     *当前等级
     *
     * Generated from protobuf field <code>int32 level = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;

        return $this;
    }

    /**
     *是否升级
     *
     * Generated from protobuf field <code>bool levelUp = 3;</code>
     * @return bool
     */
    public function getLevelUp()
    {
        return $this->levelUp;
    }

    /**
     *是否升级
     *
     * Generated from protobuf field <code>bool levelUp = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setLevelUp($var)
    {
        GPBUtil::checkBool($var);
        $this->levelUp = $var;

        return $this;
    }

    /**
     *奖励列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_PrizeInfo prizes = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPrizes()
    {
        return $this->prizes;
    }

    /**
     *奖励列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_PrizeInfo prizes = 4;</code>
     * @param \GPBClass\Message\PB_PrizeInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPrizes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_PrizeInfo::class);
        $this->prizes = $arr;

        return $this;
    }

    /**
     *下注倍数选项，升级导致变动
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BetOption betOptions = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBetOptions()
    {
        return $this->betOptions;
    }

    /**
     *下注倍数选项，升级导致变动
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BetOption betOptions = 5;</code>
     * @param \GPBClass\Message\PB_BetOption[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBetOptions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_BetOption::class);
        $this->betOptions = $arr;

        return $this;
    }

}

