<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Ping.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_Ping_Res</code>
 */
class PB_Ping_Res extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\PBPing::initOnce();
        parent::__construct();
    }

}

