<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_PrizeInfo.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_PrizeInfo</code>
 */
class PB_PrizeInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *物品ID
     *
     * Generated from protobuf field <code>string itemId = 1;</code>
     */
    private $itemId = '';
    /**
     *物品类型
     *
     * Generated from protobuf field <code>int32 type = 2;</code>
     */
    private $type = 0;
    /**
     *物品数量
     *
     * Generated from protobuf field <code>double count = 3;</code>
     */
    private $count = 0.0;
    /**
     *物品总数量(余额)
     *
     * Generated from protobuf field <code>double balance = 4;</code>
     */
    private $balance = 0.0;

    public function __construct() {
        \GPBMetadata\PBPrizeInfo::initOnce();
        parent::__construct();
    }

    /**
     *物品ID
     *
     * Generated from protobuf field <code>string itemId = 1;</code>
     * @return string
     */
    public function getItemId()
    {
        return $this->itemId;
    }

    /**
     *物品ID
     *
     * Generated from protobuf field <code>string itemId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setItemId($var)
    {
        GPBUtil::checkString($var, True);
        $this->itemId = $var;

        return $this;
    }

    /**
     *物品类型
     *
     * Generated from protobuf field <code>int32 type = 2;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     *物品类型
     *
     * Generated from protobuf field <code>int32 type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     *物品数量
     *
     * Generated from protobuf field <code>double count = 3;</code>
     * @return float
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     *物品数量
     *
     * Generated from protobuf field <code>double count = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkDouble($var);
        $this->count = $var;

        return $this;
    }

    /**
     *物品总数量(余额)
     *
     * Generated from protobuf field <code>double balance = 4;</code>
     * @return float
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     *物品总数量(余额)
     *
     * Generated from protobuf field <code>double balance = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkDouble($var);
        $this->balance = $var;

        return $this;
    }

}

