<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_RecoverLightning.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_RecoverLightning_Res</code>
 */
class PB_RecoverLightning_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *剩余spin次数
     *
     * Generated from protobuf field <code>int32 times = 1;</code>
     */
    private $times = 0;
    /**
     *已收集的元素个数
     *
     * Generated from protobuf field <code>int32 collected = 2;</code>
     */
    private $collected = 0;
    /**
     *大轴所在列(部分机台有效)
     *
     * Generated from protobuf field <code>int32 bigCol = 3;</code>
     */
    private $bigCol = 0;
    /**
     *已命中的元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 4;</code>
     */
    private $elements;

    public function __construct() {
        \GPBMetadata\PBRecoverLightning::initOnce();
        parent::__construct();
    }

    /**
     *剩余spin次数
     *
     * Generated from protobuf field <code>int32 times = 1;</code>
     * @return int
     */
    public function getTimes()
    {
        return $this->times;
    }

    /**
     *剩余spin次数
     *
     * Generated from protobuf field <code>int32 times = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTimes($var)
    {
        GPBUtil::checkInt32($var);
        $this->times = $var;

        return $this;
    }

    /**
     *已收集的元素个数
     *
     * Generated from protobuf field <code>int32 collected = 2;</code>
     * @return int
     */
    public function getCollected()
    {
        return $this->collected;
    }

    /**
     *已收集的元素个数
     *
     * Generated from protobuf field <code>int32 collected = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCollected($var)
    {
        GPBUtil::checkInt32($var);
        $this->collected = $var;

        return $this;
    }

    /**
     *大轴所在列(部分机台有效)
     *
     * Generated from protobuf field <code>int32 bigCol = 3;</code>
     * @return int
     */
    public function getBigCol()
    {
        return $this->bigCol;
    }

    /**
     *大轴所在列(部分机台有效)
     *
     * Generated from protobuf field <code>int32 bigCol = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBigCol($var)
    {
        GPBUtil::checkInt32($var);
        $this->bigCol = $var;

        return $this;
    }

    /**
     *已命中的元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getElements()
    {
        return $this->elements;
    }

    /**
     *已命中的元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 4;</code>
     * @param \GPBClass\Message\PB_SlotsElement[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_SlotsElement::class);
        $this->elements = $arr;

        return $this;
    }

}

