<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_RoleInfo.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_RoleInfo</code>
 */
class PB_RoleInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *uid
     *
     * Generated from protobuf field <code>int32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 2;</code>
     */
    private $nickname = '';
    /**
     *头像
     *
     * Generated from protobuf field <code>string avatar = 3;</code>
     */
    private $avatar = '';
    /**
     *经验值
     *
     * Generated from protobuf field <code>int64 exp = 4;</code>
     */
    private $exp = 0;
    /**
     *角色等级
     *
     * Generated from protobuf field <code>int32 level = 5;</code>
     */
    private $level = 0;
    /**
     *vip级别
     *
     * Generated from protobuf field <code>int32 vip = 6;</code>
     */
    private $vip = 0;
    /**
     *vip积分
     *
     * Generated from protobuf field <code>int64 vipPts = 7;</code>
     */
    private $vipPts = 0;
    /**
     *金币(金币)
     *
     * Generated from protobuf field <code>int64 coins = 8;</code>
     */
    private $coins = 0;
    /**
     *高级币(钻石)
     *
     * Generated from protobuf field <code>int32 diamond = 9;</code>
     */
    private $diamond = 0;
    /**
     *语言
     *
     * Generated from protobuf field <code>string lang = 10;</code>
     */
    private $lang = '';
    /**
     *等级进度
     *
     * Generated from protobuf field <code>float levelProgress = 11;</code>
     */
    private $levelProgress = 0.0;
    /**
     *vip进度
     *
     * Generated from protobuf field <code>float vipProgress = 12;</code>
     */
    private $vipProgress = 0.0;
    /**
     *平台头像
     *
     * Generated from protobuf field <code>string platformAvatar = 13;</code>
     */
    private $platformAvatar = '';

    public function __construct() {
        \GPBMetadata\PBRoleInfo::initOnce();
        parent::__construct();
    }

    /**
     *uid
     *
     * Generated from protobuf field <code>int32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     *uid
     *
     * Generated from protobuf field <code>int32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     *头像
     *
     * Generated from protobuf field <code>string avatar = 3;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     *头像
     *
     * Generated from protobuf field <code>string avatar = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar = $var;

        return $this;
    }

    /**
     *经验值
     *
     * Generated from protobuf field <code>int64 exp = 4;</code>
     * @return int|string
     */
    public function getExp()
    {
        return $this->exp;
    }

    /**
     *经验值
     *
     * Generated from protobuf field <code>int64 exp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExp($var)
    {
        GPBUtil::checkInt64($var);
        $this->exp = $var;

        return $this;
    }

    /**
     *角色等级
     *
     * Generated from protobuf field <code>int32 level = 5;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     *角色等级
     *
     * Generated from protobuf field <code>int32 level = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;

        return $this;
    }

    /**
     *vip级别
     *
     * Generated from protobuf field <code>int32 vip = 6;</code>
     * @return int
     */
    public function getVip()
    {
        return $this->vip;
    }

    /**
     *vip级别
     *
     * Generated from protobuf field <code>int32 vip = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setVip($var)
    {
        GPBUtil::checkInt32($var);
        $this->vip = $var;

        return $this;
    }

    /**
     *vip积分
     *
     * Generated from protobuf field <code>int64 vipPts = 7;</code>
     * @return int|string
     */
    public function getVipPts()
    {
        return $this->vipPts;
    }

    /**
     *vip积分
     *
     * Generated from protobuf field <code>int64 vipPts = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVipPts($var)
    {
        GPBUtil::checkInt64($var);
        $this->vipPts = $var;

        return $this;
    }

    /**
     *金币(金币)
     *
     * Generated from protobuf field <code>int64 coins = 8;</code>
     * @return int|string
     */
    public function getCoins()
    {
        return $this->coins;
    }

    /**
     *金币(金币)
     *
     * Generated from protobuf field <code>int64 coins = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCoins($var)
    {
        GPBUtil::checkInt64($var);
        $this->coins = $var;

        return $this;
    }

    /**
     *高级币(钻石)
     *
     * Generated from protobuf field <code>int32 diamond = 9;</code>
     * @return int
     */
    public function getDiamond()
    {
        return $this->diamond;
    }

    /**
     *高级币(钻石)
     *
     * Generated from protobuf field <code>int32 diamond = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setDiamond($var)
    {
        GPBUtil::checkInt32($var);
        $this->diamond = $var;

        return $this;
    }

    /**
     *语言
     *
     * Generated from protobuf field <code>string lang = 10;</code>
     * @return string
     */
    public function getLang()
    {
        return $this->lang;
    }

    /**
     *语言
     *
     * Generated from protobuf field <code>string lang = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setLang($var)
    {
        GPBUtil::checkString($var, True);
        $this->lang = $var;

        return $this;
    }

    /**
     *等级进度
     *
     * Generated from protobuf field <code>float levelProgress = 11;</code>
     * @return float
     */
    public function getLevelProgress()
    {
        return $this->levelProgress;
    }

    /**
     *等级进度
     *
     * Generated from protobuf field <code>float levelProgress = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setLevelProgress($var)
    {
        GPBUtil::checkFloat($var);
        $this->levelProgress = $var;

        return $this;
    }

    /**
     *vip进度
     *
     * Generated from protobuf field <code>float vipProgress = 12;</code>
     * @return float
     */
    public function getVipProgress()
    {
        return $this->vipProgress;
    }

    /**
     *vip进度
     *
     * Generated from protobuf field <code>float vipProgress = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setVipProgress($var)
    {
        GPBUtil::checkFloat($var);
        $this->vipProgress = $var;

        return $this;
    }

    /**
     *平台头像
     *
     * Generated from protobuf field <code>string platformAvatar = 13;</code>
     * @return string
     */
    public function getPlatformAvatar()
    {
        return $this->platformAvatar;
    }

    /**
     *平台头像
     *
     * Generated from protobuf field <code>string platformAvatar = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatformAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->platformAvatar = $var;

        return $this;
    }

}

