<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_ResumeFreeGame.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_ResumeFreeGame_Res</code>
 */
class PB_ResumeFreeGame_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *已Spin次数
     *
     * Generated from protobuf field <code>int32 spinTimes = 1;</code>
     */
    private $spinTimes = 0;
    /**
     *freespin总次数
     *
     * Generated from protobuf field <code>int32 totalTimes = 2;</code>
     */
    private $totalTimes = 0;
    /**
     *feature详情
     *
     * Generated from protobuf field <code>string detail = 3;</code>
     */
    private $detail = '';
    /**
     *所处FreeGame的totalBet
     *
     * Generated from protobuf field <code>int64 totalBet = 4;</code>
     */
    private $totalBet = 0;
    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 5;</code>
     */
    private $totalWin = 0;
    /**
     *大奖类型(结算时)
     *
     * Generated from protobuf field <code>int32 winType = 6;</code>
     */
    private $winType = 0;
    /**
     *是否结算
     *
     * Generated from protobuf field <code>bool settled = 7;</code>
     */
    private $settled = false;

    public function __construct() {
        \GPBMetadata\PBResumeFreeGame::initOnce();
        parent::__construct();
    }

    /**
     *已Spin次数
     *
     * Generated from protobuf field <code>int32 spinTimes = 1;</code>
     * @return int
     */
    public function getSpinTimes()
    {
        return $this->spinTimes;
    }

    /**
     *已Spin次数
     *
     * Generated from protobuf field <code>int32 spinTimes = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSpinTimes($var)
    {
        GPBUtil::checkInt32($var);
        $this->spinTimes = $var;

        return $this;
    }

    /**
     *freespin总次数
     *
     * Generated from protobuf field <code>int32 totalTimes = 2;</code>
     * @return int
     */
    public function getTotalTimes()
    {
        return $this->totalTimes;
    }

    /**
     *freespin总次数
     *
     * Generated from protobuf field <code>int32 totalTimes = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalTimes($var)
    {
        GPBUtil::checkInt32($var);
        $this->totalTimes = $var;

        return $this;
    }

    /**
     *feature详情
     *
     * Generated from protobuf field <code>string detail = 3;</code>
     * @return string
     */
    public function getDetail()
    {
        return $this->detail;
    }

    /**
     *feature详情
     *
     * Generated from protobuf field <code>string detail = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDetail($var)
    {
        GPBUtil::checkString($var, True);
        $this->detail = $var;

        return $this;
    }

    /**
     *所处FreeGame的totalBet
     *
     * Generated from protobuf field <code>int64 totalBet = 4;</code>
     * @return int|string
     */
    public function getTotalBet()
    {
        return $this->totalBet;
    }

    /**
     *所处FreeGame的totalBet
     *
     * Generated from protobuf field <code>int64 totalBet = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalBet($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalBet = $var;

        return $this;
    }

    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 5;</code>
     * @return int|string
     */
    public function getTotalWin()
    {
        return $this->totalWin;
    }

    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalWin($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalWin = $var;

        return $this;
    }

    /**
     *大奖类型(结算时)
     *
     * Generated from protobuf field <code>int32 winType = 6;</code>
     * @return int
     */
    public function getWinType()
    {
        return $this->winType;
    }

    /**
     *大奖类型(结算时)
     *
     * Generated from protobuf field <code>int32 winType = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setWinType($var)
    {
        GPBUtil::checkInt32($var);
        $this->winType = $var;

        return $this;
    }

    /**
     *是否结算
     *
     * Generated from protobuf field <code>bool settled = 7;</code>
     * @return bool
     */
    public function getSettled()
    {
        return $this->settled;
    }

    /**
     *是否结算
     *
     * Generated from protobuf field <code>bool settled = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setSettled($var)
    {
        GPBUtil::checkBool($var);
        $this->settled = $var;

        return $this;
    }

}

