<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SlotsHitResult.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_SlotsHitResult</code>
 */
class PB_SlotsHitResult extends \Google\Protobuf\Internal\Message
{
    /**
     *中奖lineID
     *
     * Generated from protobuf field <code>string lineId = 1;</code>
     */
    private $lineId = '';
    /**
     *中奖元素连线
     *
     * Generated from protobuf field <code>repeated int32 lineRoute = 2 [packed = true];</code>
     */
    private $lineRoute;
    /**
     *中奖元素列表
     *
     * Generated from protobuf field <code>repeated string elements = 3;</code>
     */
    private $elements;
    /**
     *奖励列表
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_SlotsLinePrize prizes = 4;</code>
     */
    private $prizes = null;

    public function __construct() {
        \GPBMetadata\PBSlotsHitResult::initOnce();
        parent::__construct();
    }

    /**
     *中奖lineID
     *
     * Generated from protobuf field <code>string lineId = 1;</code>
     * @return string
     */
    public function getLineId()
    {
        return $this->lineId;
    }

    /**
     *中奖lineID
     *
     * Generated from protobuf field <code>string lineId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLineId($var)
    {
        GPBUtil::checkString($var, True);
        $this->lineId = $var;

        return $this;
    }

    /**
     *中奖元素连线
     *
     * Generated from protobuf field <code>repeated int32 lineRoute = 2 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLineRoute()
    {
        return $this->lineRoute;
    }

    /**
     *中奖元素连线
     *
     * Generated from protobuf field <code>repeated int32 lineRoute = 2 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLineRoute($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->lineRoute = $arr;

        return $this;
    }

    /**
     *中奖元素列表
     *
     * Generated from protobuf field <code>repeated string elements = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getElements()
    {
        return $this->elements;
    }

    /**
     *中奖元素列表
     *
     * Generated from protobuf field <code>repeated string elements = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->elements = $arr;

        return $this;
    }

    /**
     *奖励列表
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_SlotsLinePrize prizes = 4;</code>
     * @return \GPBClass\Message\PB_SlotsLinePrize
     */
    public function getPrizes()
    {
        return $this->prizes;
    }

    /**
     *奖励列表
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_SlotsLinePrize prizes = 4;</code>
     * @param \GPBClass\Message\PB_SlotsLinePrize $var
     * @return $this
     */
    public function setPrizes($var)
    {
        GPBUtil::checkMessage($var, \GPBClass\Message\PB_SlotsLinePrize::class);
        $this->prizes = $var;

        return $this;
    }

}

