<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SetNickname.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_SetNickname_Res</code>
 */
class PB_SetNickname_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *用户昵称
     *
     * Generated from protobuf field <code>string nickname = 1;</code>
     */
    private $nickname = '';

    public function __construct() {
        \GPBMetadata\PBSetNickname::initOnce();
        parent::__construct();
    }

    /**
     *用户昵称
     *
     * Generated from protobuf field <code>string nickname = 1;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     *用户昵称
     *
     * Generated from protobuf field <code>string nickname = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

}

