<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SlotsBetting.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_SlotsBetting_Req</code>
 */
class PB_SlotsBetting_Req extends \Google\Protobuf\Internal\Message
{
    /**
     *下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 1;</code>
     */
    private $totalBet = 0;
    /**
     *指定中奖类型(测试专用)
     *
     * Generated from protobuf field <code>int32 winType = 2;</code>
     */
    private $winType = 0;
    /**
     *指定样本组(测试专用)
     *
     * Generated from protobuf field <code>string sampleGroup = 3;</code>
     */
    private $sampleGroup = '';
    /**
     *指定中feature，逗号分隔(测试专用)
     *
     * Generated from protobuf field <code>string feature = 4;</code>
     */
    private $feature = '';
    /**
     *是否清除当前feature(测试专用)
     *
     * Generated from protobuf field <code>bool clear = 5;</code>
     */
    private $clear = false;
    /**
     *是否必中奖(测试专用)
     *
     * Generated from protobuf field <code>bool hit = 6;</code>
     */
    private $hit = false;
    /**
     *其他命令选项(机器人专用)
     *
     * Generated from protobuf field <code>string options = 7;</code>
     */
    private $options = '';
    /**
     *广告是否已就绪
     *
     * Generated from protobuf field <code>bool isAdReady = 8;</code>
     */
    private $isAdReady = false;
    /**
     *样本库触发器Id
     *
     * Generated from protobuf field <code>string sampleLibId = 9;</code>
     */
    private $sampleLibId = '';

    public function __construct() {
        \GPBMetadata\PBSlotsBetting::initOnce();
        parent::__construct();
    }

    /**
     *下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 1;</code>
     * @return int|string
     */
    public function getTotalBet()
    {
        return $this->totalBet;
    }

    /**
     *下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalBet($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalBet = $var;

        return $this;
    }

    /**
     *指定中奖类型(测试专用)
     *
     * Generated from protobuf field <code>int32 winType = 2;</code>
     * @return int
     */
    public function getWinType()
    {
        return $this->winType;
    }

    /**
     *指定中奖类型(测试专用)
     *
     * Generated from protobuf field <code>int32 winType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWinType($var)
    {
        GPBUtil::checkInt32($var);
        $this->winType = $var;

        return $this;
    }

    /**
     *指定样本组(测试专用)
     *
     * Generated from protobuf field <code>string sampleGroup = 3;</code>
     * @return string
     */
    public function getSampleGroup()
    {
        return $this->sampleGroup;
    }

    /**
     *指定样本组(测试专用)
     *
     * Generated from protobuf field <code>string sampleGroup = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSampleGroup($var)
    {
        GPBUtil::checkString($var, True);
        $this->sampleGroup = $var;

        return $this;
    }

    /**
     *指定中feature，逗号分隔(测试专用)
     *
     * Generated from protobuf field <code>string feature = 4;</code>
     * @return string
     */
    public function getFeature()
    {
        return $this->feature;
    }

    /**
     *指定中feature，逗号分隔(测试专用)
     *
     * Generated from protobuf field <code>string feature = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFeature($var)
    {
        GPBUtil::checkString($var, True);
        $this->feature = $var;

        return $this;
    }

    /**
     *是否清除当前feature(测试专用)
     *
     * Generated from protobuf field <code>bool clear = 5;</code>
     * @return bool
     */
    public function getClear()
    {
        return $this->clear;
    }

    /**
     *是否清除当前feature(测试专用)
     *
     * Generated from protobuf field <code>bool clear = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setClear($var)
    {
        GPBUtil::checkBool($var);
        $this->clear = $var;

        return $this;
    }

    /**
     *是否必中奖(测试专用)
     *
     * Generated from protobuf field <code>bool hit = 6;</code>
     * @return bool
     */
    public function getHit()
    {
        return $this->hit;
    }

    /**
     *是否必中奖(测试专用)
     *
     * Generated from protobuf field <code>bool hit = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setHit($var)
    {
        GPBUtil::checkBool($var);
        $this->hit = $var;

        return $this;
    }

    /**
     *其他命令选项(机器人专用)
     *
     * Generated from protobuf field <code>string options = 7;</code>
     * @return string
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     *其他命令选项(机器人专用)
     *
     * Generated from protobuf field <code>string options = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setOptions($var)
    {
        GPBUtil::checkString($var, True);
        $this->options = $var;

        return $this;
    }

    /**
     *广告是否已就绪
     *
     * Generated from protobuf field <code>bool isAdReady = 8;</code>
     * @return bool
     */
    public function getIsAdReady()
    {
        return $this->isAdReady;
    }

    /**
     *广告是否已就绪
     *
     * Generated from protobuf field <code>bool isAdReady = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAdReady($var)
    {
        GPBUtil::checkBool($var);
        $this->isAdReady = $var;

        return $this;
    }

    /**
     *样本库触发器Id
     *
     * Generated from protobuf field <code>string sampleLibId = 9;</code>
     * @return string
     */
    public function getSampleLibId()
    {
        return $this->sampleLibId;
    }

    /**
     *样本库触发器Id
     *
     * Generated from protobuf field <code>string sampleLibId = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setSampleLibId($var)
    {
        GPBUtil::checkString($var, True);
        $this->sampleLibId = $var;

        return $this;
    }

}

