<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SlotsPrize.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_SlotsPrize</code>
 */
class PB_SlotsPrize extends \Google\Protobuf\Internal\Message
{
    /**
     *金币数量(不包含jackpot奖励)
     *
     * Generated from protobuf field <code>int64 coins = 1;</code>
     */
    private $coins = 0;
    /**
     *freespin次数
     *
     * Generated from protobuf field <code>int32 freespin = 2;</code>
     */
    private $freespin = 0;
    /**
     *金币倍数奖励
     *
     * Generated from protobuf field <code>int32 multiple = 3;</code>
     */
    private $multiple = 0;
    /**
     *特殊元素奖励
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 4;</code>
     */
    private $elements;
    /**
     *触发feature(可能有多个)
     *
     * Generated from protobuf field <code>repeated string features = 5;</code>
     */
    private $features;
    /**
     *feature元素奖励(可能有多个)
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_FeatureElements splitElements = 6;</code>
     */
    private $splitElements;

    public function __construct() {
        \GPBMetadata\PBSlotsPrize::initOnce();
        parent::__construct();
    }

    /**
     *金币数量(不包含jackpot奖励)
     *
     * Generated from protobuf field <code>int64 coins = 1;</code>
     * @return int|string
     */
    public function getCoins()
    {
        return $this->coins;
    }

    /**
     *金币数量(不包含jackpot奖励)
     *
     * Generated from protobuf field <code>int64 coins = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCoins($var)
    {
        GPBUtil::checkInt64($var);
        $this->coins = $var;

        return $this;
    }

    /**
     *freespin次数
     *
     * Generated from protobuf field <code>int32 freespin = 2;</code>
     * @return int
     */
    public function getFreespin()
    {
        return $this->freespin;
    }

    /**
     *freespin次数
     *
     * Generated from protobuf field <code>int32 freespin = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFreespin($var)
    {
        GPBUtil::checkInt32($var);
        $this->freespin = $var;

        return $this;
    }

    /**
     *金币倍数奖励
     *
     * Generated from protobuf field <code>int32 multiple = 3;</code>
     * @return int
     */
    public function getMultiple()
    {
        return $this->multiple;
    }

    /**
     *金币倍数奖励
     *
     * Generated from protobuf field <code>int32 multiple = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMultiple($var)
    {
        GPBUtil::checkInt32($var);
        $this->multiple = $var;

        return $this;
    }

    /**
     *特殊元素奖励
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getElements()
    {
        return $this->elements;
    }

    /**
     *特殊元素奖励
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 4;</code>
     * @param \GPBClass\Message\PB_SlotsElement[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_SlotsElement::class);
        $this->elements = $arr;

        return $this;
    }

    /**
     *触发feature(可能有多个)
     *
     * Generated from protobuf field <code>repeated string features = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFeatures()
    {
        return $this->features;
    }

    /**
     *触发feature(可能有多个)
     *
     * Generated from protobuf field <code>repeated string features = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFeatures($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->features = $arr;

        return $this;
    }

    /**
     *feature元素奖励(可能有多个)
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_FeatureElements splitElements = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSplitElements()
    {
        return $this->splitElements;
    }

    /**
     *feature元素奖励(可能有多个)
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_FeatureElements splitElements = 6;</code>
     * @param \GPBClass\Message\PB_FeatureElements[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSplitElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_FeatureElements::class);
        $this->splitElements = $arr;

        return $this;
    }

}

