<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SlotsHitResult.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_SlotsLinePrize</code>
 */
class PB_SlotsLinePrize extends \Google\Protobuf\Internal\Message
{
    /**
     *金币奖励
     *
     * Generated from protobuf field <code>int64 coins = 1;</code>
     */
    private $coins = 0;
    /**
     *倍数奖励
     *
     * Generated from protobuf field <code>int32 multiple = 2;</code>
     */
    private $multiple = 0;

    public function __construct() {
        \GPBMetadata\PBSlotsHitResult::initOnce();
        parent::__construct();
    }

    /**
     *金币奖励
     *
     * Generated from protobuf field <code>int64 coins = 1;</code>
     * @return int|string
     */
    public function getCoins()
    {
        return $this->coins;
    }

    /**
     *金币奖励
     *
     * Generated from protobuf field <code>int64 coins = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCoins($var)
    {
        GPBUtil::checkInt64($var);
        $this->coins = $var;

        return $this;
    }

    /**
     *倍数奖励
     *
     * Generated from protobuf field <code>int32 multiple = 2;</code>
     * @return int
     */
    public function getMultiple()
    {
        return $this->multiple;
    }

    /**
     *倍数奖励
     *
     * Generated from protobuf field <code>int32 multiple = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMultiple($var)
    {
        GPBUtil::checkInt32($var);
        $this->multiple = $var;

        return $this;
    }

}

