<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SlotsBetting.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_SlotsBetting_Req</code>
 */
class PB_SlotsBetting_Req extends \Google\Protobuf\Internal\Message
{
    /**
     *下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 1;</code>
     */
    private $totalBet = 0;
    /**
     *指定中奖类型(测试专用)
     *
     * Generated from protobuf field <code>int32 winType = 2;</code>
     */
    private $winType = 0;
    /**
     *指定中feature，逗号分隔(测试专用)
     *
     * Generated from protobuf field <code>string feature = 3;</code>
     */
    private $feature = '';
    /**
     *是否清除当前feature(测试专用)
     *
     * Generated from protobuf field <code>bool clear = 4;</code>
     */
    private $clear = false;
    /**
     *是否必中奖(测试专用)
     *
     * Generated from protobuf field <code>bool hit = 5;</code>
     */
    private $hit = false;

    public function __construct() {
        \GPBMetadata\PBSlotsBetting::initOnce();
        parent::__construct();
    }

    /**
     *下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 1;</code>
     * @return int|string
     */
    public function getTotalBet()
    {
        return $this->totalBet;
    }

    /**
     *下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalBet($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalBet = $var;

        return $this;
    }

    /**
     *指定中奖类型(测试专用)
     *
     * Generated from protobuf field <code>int32 winType = 2;</code>
     * @return int
     */
    public function getWinType()
    {
        return $this->winType;
    }

    /**
     *指定中奖类型(测试专用)
     *
     * Generated from protobuf field <code>int32 winType = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setWinType($var)
    {
        GPBUtil::checkInt32($var);
        $this->winType = $var;

        return $this;
    }

    /**
     *指定中feature，逗号分隔(测试专用)
     *
     * Generated from protobuf field <code>string feature = 3;</code>
     * @return string
     */
    public function getFeature()
    {
        return $this->feature;
    }

    /**
     *指定中feature，逗号分隔(测试专用)
     *
     * Generated from protobuf field <code>string feature = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFeature($var)
    {
        GPBUtil::checkString($var, True);
        $this->feature = $var;

        return $this;
    }

    /**
     *是否清除当前feature(测试专用)
     *
     * Generated from protobuf field <code>bool clear = 4;</code>
     * @return bool
     */
    public function getClear()
    {
        return $this->clear;
    }

    /**
     *是否清除当前feature(测试专用)
     *
     * Generated from protobuf field <code>bool clear = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setClear($var)
    {
        GPBUtil::checkBool($var);
        $this->clear = $var;

        return $this;
    }

    /**
     *是否必中奖(测试专用)
     *
     * Generated from protobuf field <code>bool hit = 5;</code>
     * @return bool
     */
    public function getHit()
    {
        return $this->hit;
    }

    /**
     *是否必中奖(测试专用)
     *
     * Generated from protobuf field <code>bool hit = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setHit($var)
    {
        GPBUtil::checkBool($var);
        $this->hit = $var;

        return $this;
    }

}

