<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SlotsResultSteps.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_SlotsResultSteps</code>
 */
class PB_SlotsResultSteps extends \Google\Protobuf\Internal\Message
{
    /**
     *步骤序号
     *
     * Generated from protobuf field <code>int32 step = 1;</code>
     */
    private $step = 0;
    /**
     *元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 2;</code>
     */
    private $elements;
    /**
     *中奖结果
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsHitResult results = 3;</code>
     */
    private $results;
    /**
     *本步骤奖励
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_SlotsPrize prizes = 4;</code>
     */
    private $prizes = null;
    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 5;</code>
     */
    private $totalWin = 0;

    public function __construct() {
        \GPBMetadata\PBSlotsResultSteps::initOnce();
        parent::__construct();
    }

    /**
     *步骤序号
     *
     * Generated from protobuf field <code>int32 step = 1;</code>
     * @return int
     */
    public function getStep()
    {
        return $this->step;
    }

    /**
     *步骤序号
     *
     * Generated from protobuf field <code>int32 step = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStep($var)
    {
        GPBUtil::checkInt32($var);
        $this->step = $var;

        return $this;
    }

    /**
     *元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getElements()
    {
        return $this->elements;
    }

    /**
     *元素列表
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement elements = 2;</code>
     * @param \GPBClass\Message\PB_SlotsElement[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_SlotsElement::class);
        $this->elements = $arr;

        return $this;
    }

    /**
     *中奖结果
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsHitResult results = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResults()
    {
        return $this->results;
    }

    /**
     *中奖结果
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsHitResult results = 3;</code>
     * @param \GPBClass\Message\PB_SlotsHitResult[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_SlotsHitResult::class);
        $this->results = $arr;

        return $this;
    }

    /**
     *本步骤奖励
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_SlotsPrize prizes = 4;</code>
     * @return \GPBClass\Message\PB_SlotsPrize
     */
    public function getPrizes()
    {
        return $this->prizes;
    }

    /**
     *本步骤奖励
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_SlotsPrize prizes = 4;</code>
     * @param \GPBClass\Message\PB_SlotsPrize $var
     * @return $this
     */
    public function setPrizes($var)
    {
        GPBUtil::checkMessage($var, \GPBClass\Message\PB_SlotsPrize::class);
        $this->prizes = $var;

        return $this;
    }

    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 5;</code>
     * @return int|string
     */
    public function getTotalWin()
    {
        return $this->totalWin;
    }

    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalWin($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalWin = $var;

        return $this;
    }

}

