<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SlotsElement.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_SlotsElement</code>
 */
class PB_SlotsElement extends \Google\Protobuf\Internal\Message
{
    /**
     *元素ID
     *
     * Generated from protobuf field <code>string elementId = 1;</code>
     */
    private $elementId = '';
    /**
     *元素所在列
     *
     * Generated from protobuf field <code>int32 col = 2;</code>
     */
    private $col = 0;
    /**
     *元素所在行
     *
     * Generated from protobuf field <code>int32 row = 3;</code>
     */
    private $row = 0;
    /**
     *附带值（可能包含多个值，逗号分隔）
     *
     * Generated from protobuf field <code>string value = 4;</code>
     */
    private $value = '';

    public function __construct() {
        \GPBMetadata\PBSlotsElement::initOnce();
        parent::__construct();
    }

    /**
     *元素ID
     *
     * Generated from protobuf field <code>string elementId = 1;</code>
     * @return string
     */
    public function getElementId()
    {
        return $this->elementId;
    }

    /**
     *元素ID
     *
     * Generated from protobuf field <code>string elementId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setElementId($var)
    {
        GPBUtil::checkString($var, True);
        $this->elementId = $var;

        return $this;
    }

    /**
     *元素所在列
     *
     * Generated from protobuf field <code>int32 col = 2;</code>
     * @return int
     */
    public function getCol()
    {
        return $this->col;
    }

    /**
     *元素所在列
     *
     * Generated from protobuf field <code>int32 col = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCol($var)
    {
        GPBUtil::checkInt32($var);
        $this->col = $var;

        return $this;
    }

    /**
     *元素所在行
     *
     * Generated from protobuf field <code>int32 row = 3;</code>
     * @return int
     */
    public function getRow()
    {
        return $this->row;
    }

    /**
     *元素所在行
     *
     * Generated from protobuf field <code>int32 row = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRow($var)
    {
        GPBUtil::checkInt32($var);
        $this->row = $var;

        return $this;
    }

    /**
     *附带值（可能包含多个值，逗号分隔）
     *
     * Generated from protobuf field <code>string value = 4;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     *附带值（可能包含多个值，逗号分隔）
     *
     * Generated from protobuf field <code>string value = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

