<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SlotsBetting.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_SlotsBetting_Res</code>
 */
class PB_SlotsBetting_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *本次花费金币
     *
     * Generated from protobuf field <code>int64 cost = 1;</code>
     */
    private $cost = 0;
    /**
     *本次下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 2;</code>
     */
    private $totalBet = 0;
    /**
     *待恢复的下注额
     *
     * Generated from protobuf field <code>int64 resumeBet = 3;</code>
     */
    private $resumeBet = 0;
    /**
     *是否是freespin
     *
     * Generated from protobuf field <code>bool isFreeSpin = 4;</code>
     */
    private $isFreeSpin = false;
    /**
     *是否是最后一次freespin
     *
     * Generated from protobuf field <code>bool isLastFreeSpin = 5;</code>
     */
    private $isLastFreeSpin = false;
    /**
     *第几次spin(对freespin有效)
     *
     * Generated from protobuf field <code>int32 spinTimes = 6;</code>
     */
    private $spinTimes = 0;
    /**
     *当前feature
     *
     * Generated from protobuf field <code>string feature = 7;</code>
     */
    private $feature = '';
    /**
     *中奖结果(可能有多步)
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsResultSteps resultSteps = 8;</code>
     */
    private $resultSteps;
    /**
     *上次spin后遗留的sticky元素(如果可能发生移动，则是移动后的位置)
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement stickyElements = 9;</code>
     */
    private $stickyElements;
    /**
     *下次spin轴上的stack替换元素
     *
     * Generated from protobuf field <code>repeated int32 nextStacks = 10 [packed = true];</code>
     */
    private $nextStacks;
    /**
     *本次spin附加消息列表
     *
     * Generated from protobuf field <code>repeated int32 nextMsgIds = 11 [packed = true];</code>
     */
    private $nextMsgIds;
    /**
     *本次中奖赢得数额
     *
     * Generated from protobuf field <code>int64 winCoins = 12;</code>
     */
    private $winCoins = 0;
    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 13;</code>
     */
    private $totalWin = 0;
    /**
     *本次中奖类型(BIG WIN | MEGA WIN...)
     *
     * Generated from protobuf field <code>int32 winType = 14;</code>
     */
    private $winType = 0;
    /**
     *TotalWin中奖类型(BIG WIN | MEGA WIN...)
     *
     * Generated from protobuf field <code>int32 totalWinType = 15;</code>
     */
    private $totalWinType = 0;
    /**
     *金币余额(最新值)
     *
     * Generated from protobuf field <code>int64 balance = 17;</code>
     */
    private $balance = 0;
    /**
     *是否结算
     *
     * Generated from protobuf field <code>bool settled = 18;</code>
     */
    private $settled = false;
    /**
     * 附加消息
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_MessageBase64List nextMessages = 19;</code>
     */
    private $nextMessages;

    public function __construct() {
        \GPBMetadata\PBSlotsBetting::initOnce();
        parent::__construct();
    }

    /**
     *本次花费金币
     *
     * Generated from protobuf field <code>int64 cost = 1;</code>
     * @return int|string
     */
    public function getCost()
    {
        return $this->cost;
    }

    /**
     *本次花费金币
     *
     * Generated from protobuf field <code>int64 cost = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCost($var)
    {
        GPBUtil::checkInt64($var);
        $this->cost = $var;

        return $this;
    }

    /**
     *本次下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 2;</code>
     * @return int|string
     */
    public function getTotalBet()
    {
        return $this->totalBet;
    }

    /**
     *本次下注额
     *
     * Generated from protobuf field <code>int64 totalBet = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalBet($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalBet = $var;

        return $this;
    }

    /**
     *待恢复的下注额
     *
     * Generated from protobuf field <code>int64 resumeBet = 3;</code>
     * @return int|string
     */
    public function getResumeBet()
    {
        return $this->resumeBet;
    }

    /**
     *待恢复的下注额
     *
     * Generated from protobuf field <code>int64 resumeBet = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setResumeBet($var)
    {
        GPBUtil::checkInt64($var);
        $this->resumeBet = $var;

        return $this;
    }

    /**
     *是否是freespin
     *
     * Generated from protobuf field <code>bool isFreeSpin = 4;</code>
     * @return bool
     */
    public function getIsFreeSpin()
    {
        return $this->isFreeSpin;
    }

    /**
     *是否是freespin
     *
     * Generated from protobuf field <code>bool isFreeSpin = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFreeSpin($var)
    {
        GPBUtil::checkBool($var);
        $this->isFreeSpin = $var;

        return $this;
    }

    /**
     *是否是最后一次freespin
     *
     * Generated from protobuf field <code>bool isLastFreeSpin = 5;</code>
     * @return bool
     */
    public function getIsLastFreeSpin()
    {
        return $this->isLastFreeSpin;
    }

    /**
     *是否是最后一次freespin
     *
     * Generated from protobuf field <code>bool isLastFreeSpin = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLastFreeSpin($var)
    {
        GPBUtil::checkBool($var);
        $this->isLastFreeSpin = $var;

        return $this;
    }

    /**
     *第几次spin(对freespin有效)
     *
     * Generated from protobuf field <code>int32 spinTimes = 6;</code>
     * @return int
     */
    public function getSpinTimes()
    {
        return $this->spinTimes;
    }

    /**
     *第几次spin(对freespin有效)
     *
     * Generated from protobuf field <code>int32 spinTimes = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSpinTimes($var)
    {
        GPBUtil::checkInt32($var);
        $this->spinTimes = $var;

        return $this;
    }

    /**
     *当前feature
     *
     * Generated from protobuf field <code>string feature = 7;</code>
     * @return string
     */
    public function getFeature()
    {
        return $this->feature;
    }

    /**
     *当前feature
     *
     * Generated from protobuf field <code>string feature = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFeature($var)
    {
        GPBUtil::checkString($var, True);
        $this->feature = $var;

        return $this;
    }

    /**
     *中奖结果(可能有多步)
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsResultSteps resultSteps = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResultSteps()
    {
        return $this->resultSteps;
    }

    /**
     *中奖结果(可能有多步)
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsResultSteps resultSteps = 8;</code>
     * @param \GPBClass\Message\PB_SlotsResultSteps[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResultSteps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_SlotsResultSteps::class);
        $this->resultSteps = $arr;

        return $this;
    }

    /**
     *上次spin后遗留的sticky元素(如果可能发生移动，则是移动后的位置)
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement stickyElements = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStickyElements()
    {
        return $this->stickyElements;
    }

    /**
     *上次spin后遗留的sticky元素(如果可能发生移动，则是移动后的位置)
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_SlotsElement stickyElements = 9;</code>
     * @param \GPBClass\Message\PB_SlotsElement[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStickyElements($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_SlotsElement::class);
        $this->stickyElements = $arr;

        return $this;
    }

    /**
     *下次spin轴上的stack替换元素
     *
     * Generated from protobuf field <code>repeated int32 nextStacks = 10 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNextStacks()
    {
        return $this->nextStacks;
    }

    /**
     *下次spin轴上的stack替换元素
     *
     * Generated from protobuf field <code>repeated int32 nextStacks = 10 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNextStacks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->nextStacks = $arr;

        return $this;
    }

    /**
     *本次spin附加消息列表
     *
     * Generated from protobuf field <code>repeated int32 nextMsgIds = 11 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNextMsgIds()
    {
        return $this->nextMsgIds;
    }

    /**
     *本次spin附加消息列表
     *
     * Generated from protobuf field <code>repeated int32 nextMsgIds = 11 [packed = true];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNextMsgIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->nextMsgIds = $arr;

        return $this;
    }

    /**
     *本次中奖赢得数额
     *
     * Generated from protobuf field <code>int64 winCoins = 12;</code>
     * @return int|string
     */
    public function getWinCoins()
    {
        return $this->winCoins;
    }

    /**
     *本次中奖赢得数额
     *
     * Generated from protobuf field <code>int64 winCoins = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWinCoins($var)
    {
        GPBUtil::checkInt64($var);
        $this->winCoins = $var;

        return $this;
    }

    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 13;</code>
     * @return int|string
     */
    public function getTotalWin()
    {
        return $this->totalWin;
    }

    /**
     *当前TotalWin
     *
     * Generated from protobuf field <code>int64 totalWin = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalWin($var)
    {
        GPBUtil::checkInt64($var);
        $this->totalWin = $var;

        return $this;
    }

    /**
     *本次中奖类型(BIG WIN | MEGA WIN...)
     *
     * Generated from protobuf field <code>int32 winType = 14;</code>
     * @return int
     */
    public function getWinType()
    {
        return $this->winType;
    }

    /**
     *本次中奖类型(BIG WIN | MEGA WIN...)
     *
     * Generated from protobuf field <code>int32 winType = 14;</code>
     * @param int $var
     * @return $this
     */
    public function setWinType($var)
    {
        GPBUtil::checkInt32($var);
        $this->winType = $var;

        return $this;
    }

    /**
     *TotalWin中奖类型(BIG WIN | MEGA WIN...)
     *
     * Generated from protobuf field <code>int32 totalWinType = 15;</code>
     * @return int
     */
    public function getTotalWinType()
    {
        return $this->totalWinType;
    }

    /**
     *TotalWin中奖类型(BIG WIN | MEGA WIN...)
     *
     * Generated from protobuf field <code>int32 totalWinType = 15;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalWinType($var)
    {
        GPBUtil::checkInt32($var);
        $this->totalWinType = $var;

        return $this;
    }

    /**
     *金币余额(最新值)
     *
     * Generated from protobuf field <code>int64 balance = 17;</code>
     * @return int|string
     */
    public function getBalance()
    {
        return $this->balance;
    }

    /**
     *金币余额(最新值)
     *
     * Generated from protobuf field <code>int64 balance = 17;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBalance($var)
    {
        GPBUtil::checkInt64($var);
        $this->balance = $var;

        return $this;
    }

    /**
     *是否结算
     *
     * Generated from protobuf field <code>bool settled = 18;</code>
     * @return bool
     */
    public function getSettled()
    {
        return $this->settled;
    }

    /**
     *是否结算
     *
     * Generated from protobuf field <code>bool settled = 18;</code>
     * @param bool $var
     * @return $this
     */
    public function setSettled($var)
    {
        GPBUtil::checkBool($var);
        $this->settled = $var;

        return $this;
    }

    /**
     * 附加消息
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_MessageBase64List nextMessages = 19;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNextMessages()
    {
        return $this->nextMessages;
    }

    /**
     * 附加消息
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_MessageBase64List nextMessages = 19;</code>
     * @param \GPBClass\Message\PB_MessageBase64List[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNextMessages($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_MessageBase64List::class);
        $this->nextMessages = $arr;

        return $this;
    }

}

