<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_UserLogin.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_UserLogin_Req</code>
 */
class PB_UserLogin_Req extends \Google\Protobuf\Internal\Message
{
    /**
     *平台用户的标识
     *
     * Generated from protobuf field <code>string openid = 1;</code>
     */
    private $openid = '';
    /**
     *平台验证token
     *
     * Generated from protobuf field <code>string token = 2;</code>
     */
    private $token = '';
    /**
     *用户所属平台
     *
     * Generated from protobuf field <code>int32 platform = 3;</code>
     */
    private $platform = 0;
    /**
     *客户端版本号
     *
     * Generated from protobuf field <code>string version = 4;</code>
     */
    private $version = '';
    /**
     *设备ID
     *
     * Generated from protobuf field <code>string deviceId = 5;</code>
     */
    private $deviceId = '';
    /**
     *设备Token
     *
     * Generated from protobuf field <code>string deviceToken = 6;</code>
     */
    private $deviceToken = '';
    /**
     *广告追踪ID
     *
     * Generated from protobuf field <code>string idfa = 7;</code>
     */
    private $idfa = '';
    /**
     *appsflyerId
     *
     * Generated from protobuf field <code>string appsflyerId = 8;</code>
     */
    private $appsflyerId = '';

    public function __construct() {
        \GPBMetadata\PBUserLogin::initOnce();
        parent::__construct();
    }

    /**
     *平台用户的标识
     *
     * Generated from protobuf field <code>string openid = 1;</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     *平台用户的标识
     *
     * Generated from protobuf field <code>string openid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     *平台验证token
     *
     * Generated from protobuf field <code>string token = 2;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *平台验证token
     *
     * Generated from protobuf field <code>string token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *用户所属平台
     *
     * Generated from protobuf field <code>int32 platform = 3;</code>
     * @return int
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     *用户所属平台
     *
     * Generated from protobuf field <code>int32 platform = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkInt32($var);
        $this->platform = $var;

        return $this;
    }

    /**
     *客户端版本号
     *
     * Generated from protobuf field <code>string version = 4;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     *客户端版本号
     *
     * Generated from protobuf field <code>string version = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

    /**
     *设备ID
     *
     * Generated from protobuf field <code>string deviceId = 5;</code>
     * @return string
     */
    public function getDeviceId()
    {
        return $this->deviceId;
    }

    /**
     *设备ID
     *
     * Generated from protobuf field <code>string deviceId = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkString($var, True);
        $this->deviceId = $var;

        return $this;
    }

    /**
     *设备Token
     *
     * Generated from protobuf field <code>string deviceToken = 6;</code>
     * @return string
     */
    public function getDeviceToken()
    {
        return $this->deviceToken;
    }

    /**
     *设备Token
     *
     * Generated from protobuf field <code>string deviceToken = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->deviceToken = $var;

        return $this;
    }

    /**
     *广告追踪ID
     *
     * Generated from protobuf field <code>string idfa = 7;</code>
     * @return string
     */
    public function getIdfa()
    {
        return $this->idfa;
    }

    /**
     *广告追踪ID
     *
     * Generated from protobuf field <code>string idfa = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setIdfa($var)
    {
        GPBUtil::checkString($var, True);
        $this->idfa = $var;

        return $this;
    }

    /**
     *appsflyerId
     *
     * Generated from protobuf field <code>string appsflyerId = 8;</code>
     * @return string
     */
    public function getAppsflyerId()
    {
        return $this->appsflyerId;
    }

    /**
     *appsflyerId
     *
     * Generated from protobuf field <code>string appsflyerId = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAppsflyerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->appsflyerId = $var;

        return $this;
    }

}

