<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_UserBind.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_UserBind_Res</code>
 */
class PB_UserBind_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *绑定后的用户ID
     *
     * Generated from protobuf field <code>int32 uid = 1;</code>
     */
    private $uid = 0;
    /**
     *绑定后的昵称
     *
     * Generated from protobuf field <code>string nickname = 2;</code>
     */
    private $nickname = '';
    /**
     *绑定后的头像
     *
     * Generated from protobuf field <code>string avatar = 3;</code>
     */
    private $avatar = '';

    public function __construct() {
        \GPBMetadata\PBUserBind::initOnce();
        parent::__construct();
    }

    /**
     *绑定后的用户ID
     *
     * Generated from protobuf field <code>int32 uid = 1;</code>
     * @return int
     */
    public function getUid()
    {
        return $this->uid;
    }

    /**
     *绑定后的用户ID
     *
     * Generated from protobuf field <code>int32 uid = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUid($var)
    {
        GPBUtil::checkInt32($var);
        $this->uid = $var;

        return $this;
    }

    /**
     *绑定后的昵称
     *
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     *绑定后的昵称
     *
     * Generated from protobuf field <code>string nickname = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     *绑定后的头像
     *
     * Generated from protobuf field <code>string avatar = 3;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     *绑定后的头像
     *
     * Generated from protobuf field <code>string avatar = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar = $var;

        return $this;
    }

}

