<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_UserLogin.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_UserLogin_Res</code>
 */
class PB_UserLogin_Res extends \Google\Protobuf\Internal\Message
{
    /**
     *sessionId
     *
     * Generated from protobuf field <code>string sessionId = 1;</code>
     */
    private $sessionId = '';
    /**
     *角色基本信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_RoleInfo roleInfo = 2;</code>
     */
    private $roleInfo = null;
    /**
     *Buff信息
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BuffInfo buffs = 3;</code>
     */
    private $buffs;
    /**
     *当前登录类型 0-普通登录 1-首次登录 2-今天首次登录
     *
     * Generated from protobuf field <code>int32 loginType = 4;</code>
     */
    private $loginType = 0;
    /**
     *当前系统时间戳
     *
     * Generated from protobuf field <code>int32 systemTime = 5;</code>
     */
    private $systemTime = 0;
    /**
     *次日零点时间戳
     *
     * Generated from protobuf field <code>int32 tomorrowTime = 6;</code>
     */
    private $tomorrowTime = 0;
    /**
     *用户注册时间戳
     *
     * Generated from protobuf field <code>int32 regTime = 7;</code>
     */
    private $regTime = 0;
    /**
     *用户账号平台类型
     *
     * Generated from protobuf field <code>int32 platform = 8;</code>
     */
    private $platform = 0;
    /**
     *用户登录总天数
     *
     * Generated from protobuf field <code>int32 loginDays = 9;</code>
     */
    private $loginDays = 0;
    /**
     *用户常规连续登录天数
     *
     * Generated from protobuf field <code>int32 regularContinuedLoginDays = 10;</code>
     */
    private $regularContinuedLoginDays = 0;
    /**
     *广告开放等级
     *
     * Generated from protobuf field <code>int32 adLevelLock = 11;</code>
     */
    private $adLevelLock = 0;

    public function __construct() {
        \GPBMetadata\PBUserLogin::initOnce();
        parent::__construct();
    }

    /**
     *sessionId
     *
     * Generated from protobuf field <code>string sessionId = 1;</code>
     * @return string
     */
    public function getSessionId()
    {
        return $this->sessionId;
    }

    /**
     *sessionId
     *
     * Generated from protobuf field <code>string sessionId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->sessionId = $var;

        return $this;
    }

    /**
     *角色基本信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_RoleInfo roleInfo = 2;</code>
     * @return \GPBClass\Message\PB_RoleInfo
     */
    public function getRoleInfo()
    {
        return $this->roleInfo;
    }

    /**
     *角色基本信息
     *
     * Generated from protobuf field <code>.GPBClass.Message.PB_RoleInfo roleInfo = 2;</code>
     * @param \GPBClass\Message\PB_RoleInfo $var
     * @return $this
     */
    public function setRoleInfo($var)
    {
        GPBUtil::checkMessage($var, \GPBClass\Message\PB_RoleInfo::class);
        $this->roleInfo = $var;

        return $this;
    }

    /**
     *Buff信息
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BuffInfo buffs = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBuffs()
    {
        return $this->buffs;
    }

    /**
     *Buff信息
     *
     * Generated from protobuf field <code>repeated .GPBClass.Message.PB_BuffInfo buffs = 3;</code>
     * @param \GPBClass\Message\PB_BuffInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBuffs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \GPBClass\Message\PB_BuffInfo::class);
        $this->buffs = $arr;

        return $this;
    }

    /**
     *当前登录类型 0-普通登录 1-首次登录 2-今天首次登录
     *
     * Generated from protobuf field <code>int32 loginType = 4;</code>
     * @return int
     */
    public function getLoginType()
    {
        return $this->loginType;
    }

    /**
     *当前登录类型 0-普通登录 1-首次登录 2-今天首次登录
     *
     * Generated from protobuf field <code>int32 loginType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLoginType($var)
    {
        GPBUtil::checkInt32($var);
        $this->loginType = $var;

        return $this;
    }

    /**
     *当前系统时间戳
     *
     * Generated from protobuf field <code>int32 systemTime = 5;</code>
     * @return int
     */
    public function getSystemTime()
    {
        return $this->systemTime;
    }

    /**
     *当前系统时间戳
     *
     * Generated from protobuf field <code>int32 systemTime = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setSystemTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->systemTime = $var;

        return $this;
    }

    /**
     *次日零点时间戳
     *
     * Generated from protobuf field <code>int32 tomorrowTime = 6;</code>
     * @return int
     */
    public function getTomorrowTime()
    {
        return $this->tomorrowTime;
    }

    /**
     *次日零点时间戳
     *
     * Generated from protobuf field <code>int32 tomorrowTime = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setTomorrowTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->tomorrowTime = $var;

        return $this;
    }

    /**
     *用户注册时间戳
     *
     * Generated from protobuf field <code>int32 regTime = 7;</code>
     * @return int
     */
    public function getRegTime()
    {
        return $this->regTime;
    }

    /**
     *用户注册时间戳
     *
     * Generated from protobuf field <code>int32 regTime = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setRegTime($var)
    {
        GPBUtil::checkInt32($var);
        $this->regTime = $var;

        return $this;
    }

    /**
     *用户账号平台类型
     *
     * Generated from protobuf field <code>int32 platform = 8;</code>
     * @return int
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     *用户账号平台类型
     *
     * Generated from protobuf field <code>int32 platform = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkInt32($var);
        $this->platform = $var;

        return $this;
    }

    /**
     *用户登录总天数
     *
     * Generated from protobuf field <code>int32 loginDays = 9;</code>
     * @return int
     */
    public function getLoginDays()
    {
        return $this->loginDays;
    }

    /**
     *用户登录总天数
     *
     * Generated from protobuf field <code>int32 loginDays = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setLoginDays($var)
    {
        GPBUtil::checkInt32($var);
        $this->loginDays = $var;

        return $this;
    }

    /**
     *用户常规连续登录天数
     *
     * Generated from protobuf field <code>int32 regularContinuedLoginDays = 10;</code>
     * @return int
     */
    public function getRegularContinuedLoginDays()
    {
        return $this->regularContinuedLoginDays;
    }

    /**
     *用户常规连续登录天数
     *
     * Generated from protobuf field <code>int32 regularContinuedLoginDays = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setRegularContinuedLoginDays($var)
    {
        GPBUtil::checkInt32($var);
        $this->regularContinuedLoginDays = $var;

        return $this;
    }

    /**
     *广告开放等级
     *
     * Generated from protobuf field <code>int32 adLevelLock = 11;</code>
     * @return int
     */
    public function getAdLevelLock()
    {
        return $this->adLevelLock;
    }

    /**
     *广告开放等级
     *
     * Generated from protobuf field <code>int32 adLevelLock = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setAdLevelLock($var)
    {
        GPBUtil::checkInt32($var);
        $this->adLevelLock = $var;

        return $this;
    }

}

