<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_UserBind.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_UserBind_Req</code>
 */
class PB_UserBind_Req extends \Google\Protobuf\Internal\Message
{
    /**
     *fb用户的标识
     *
     * Generated from protobuf field <code>string openid = 1;</code>
     */
    private $openid = '';
    /**
     *fb验证token
     *
     * Generated from protobuf field <code>string token = 2;</code>
     */
    private $token = '';
    /**
     *平台标识
     *
     * Generated from protobuf field <code>int32 platform = 3;</code>
     */
    private $platform = 0;

    public function __construct() {
        \GPBMetadata\PBUserBind::initOnce();
        parent::__construct();
    }

    /**
     *fb用户的标识
     *
     * Generated from protobuf field <code>string openid = 1;</code>
     * @return string
     */
    public function getOpenid()
    {
        return $this->openid;
    }

    /**
     *fb用户的标识
     *
     * Generated from protobuf field <code>string openid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOpenid($var)
    {
        GPBUtil::checkString($var, True);
        $this->openid = $var;

        return $this;
    }

    /**
     *fb验证token
     *
     * Generated from protobuf field <code>string token = 2;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *fb验证token
     *
     * Generated from protobuf field <code>string token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *平台标识
     *
     * Generated from protobuf field <code>int32 platform = 3;</code>
     * @return int
     */
    public function getPlatform()
    {
        return $this->platform;
    }

    /**
     *平台标识
     *
     * Generated from protobuf field <code>int32 platform = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPlatform($var)
    {
        GPBUtil::checkInt32($var);
        $this->platform = $var;

        return $this;
    }

}

