<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_WheelItemInfo.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_WheelItemInfo</code>
 */
class PB_WheelItemInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *元素位置
     *
     * Generated from protobuf field <code>int32 pos = 1;</code>
     */
    private $pos = 0;
    /**
     *元素名称
     *
     * Generated from protobuf field <code>string itemName = 2;</code>
     */
    private $itemName = '';
    /**
     *元素类型
     *
     * Generated from protobuf field <code>string itemType = 3;</code>
     */
    private $itemType = '';
    /**
     *元素值
     *
     * Generated from protobuf field <code>string itemValue = 4;</code>
     */
    private $itemValue = '';
    /**
     *关联的物品ID
     *
     * Generated from protobuf field <code>string itemId = 5;</code>
     */
    private $itemId = '';

    public function __construct() {
        \GPBMetadata\PBWheelItemInfo::initOnce();
        parent::__construct();
    }

    /**
     *元素位置
     *
     * Generated from protobuf field <code>int32 pos = 1;</code>
     * @return int
     */
    public function getPos()
    {
        return $this->pos;
    }

    /**
     *元素位置
     *
     * Generated from protobuf field <code>int32 pos = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPos($var)
    {
        GPBUtil::checkInt32($var);
        $this->pos = $var;

        return $this;
    }

    /**
     *元素名称
     *
     * Generated from protobuf field <code>string itemName = 2;</code>
     * @return string
     */
    public function getItemName()
    {
        return $this->itemName;
    }

    /**
     *元素名称
     *
     * Generated from protobuf field <code>string itemName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setItemName($var)
    {
        GPBUtil::checkString($var, True);
        $this->itemName = $var;

        return $this;
    }

    /**
     *元素类型
     *
     * Generated from protobuf field <code>string itemType = 3;</code>
     * @return string
     */
    public function getItemType()
    {
        return $this->itemType;
    }

    /**
     *元素类型
     *
     * Generated from protobuf field <code>string itemType = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setItemType($var)
    {
        GPBUtil::checkString($var, True);
        $this->itemType = $var;

        return $this;
    }

    /**
     *元素值
     *
     * Generated from protobuf field <code>string itemValue = 4;</code>
     * @return string
     */
    public function getItemValue()
    {
        return $this->itemValue;
    }

    /**
     *元素值
     *
     * Generated from protobuf field <code>string itemValue = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setItemValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->itemValue = $var;

        return $this;
    }

    /**
     *关联的物品ID
     *
     * Generated from protobuf field <code>string itemId = 5;</code>
     * @return string
     */
    public function getItemId()
    {
        return $this->itemId;
    }

    /**
     *关联的物品ID
     *
     * Generated from protobuf field <code>string itemId = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setItemId($var)
    {
        GPBUtil::checkString($var, True);
        $this->itemId = $var;

        return $this;
    }

}

