<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_WheelSpin.proto

namespace GPBClass\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>GPBClass.Message.PB_WheelSpin_Req</code>
 */
class PB_WheelSpin_Req extends \Google\Protobuf\Internal\Message
{
    /**
     *转盘ID
     *
     * Generated from protobuf field <code>string wheelId = 1;</code>
     */
    private $wheelId = '';
    /**
     *指定中奖位置(测试专用)
     *
     * Generated from protobuf field <code>int32 pos = 2;</code>
     */
    private $pos = 0;

    public function __construct() {
        \GPBMetadata\PBWheelSpin::initOnce();
        parent::__construct();
    }

    /**
     *转盘ID
     *
     * Generated from protobuf field <code>string wheelId = 1;</code>
     * @return string
     */
    public function getWheelId()
    {
        return $this->wheelId;
    }

    /**
     *转盘ID
     *
     * Generated from protobuf field <code>string wheelId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWheelId($var)
    {
        GPBUtil::checkString($var, True);
        $this->wheelId = $var;

        return $this;
    }

    /**
     *指定中奖位置(测试专用)
     *
     * Generated from protobuf field <code>int32 pos = 2;</code>
     * @return int
     */
    public function getPos()
    {
        return $this->pos;
    }

    /**
     *指定中奖位置(测试专用)
     *
     * Generated from protobuf field <code>int32 pos = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPos($var)
    {
        GPBUtil::checkInt32($var);
        $this->pos = $var;

        return $this;
    }

}

