<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_BetOption.proto

namespace GPBMetadata;

class PBBetOption
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a650a1250425f4265744f7074696f6e2e70726f746f1210475042436c61" .
            "73732e4d65737361676522350a0c50425f4265744f7074696f6e12130a0b" .
            "6265744d756c7469706c6518012001280312100a08746f74616c42657418" .
            "0220012803620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

