<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_CheckModuleVersion.proto

namespace GPBMetadata;

class PBCheckModuleVersion
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afb010a1b50425f436865636b4d6f64756c6556657273696f6e2e70726f" .
            "746f1210475042436c6173732e4d65737361676522500a1950425f436865" .
            "636b4d6f64756c6556657273696f6e5f526571120e0a066d6f64756c6518" .
            "012001280912120a0a62696756657273696f6e180220012809120f0a0776" .
            "657273696f6e18032001280522700a1950425f436865636b4d6f64756c65" .
            "56657273696f6e5f526573120e0a066d6f64756c65180120012809120f0a" .
            "0776657273696f6e18022001280512120a0a7061636b61676555726c1803" .
            "2001280912110a09686173557064617465180420012808120b0a036d6435" .
            "180520012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

