<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_CheckAppVersion.proto

namespace GPBMetadata;

class PBCheckAppVersion
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a95020a1850425f436865636b41707056657273696f6e2e70726f746f12" .
            "10475042436c6173732e4d65737361676522510a1650425f436865636b41" .
            "707056657273696f6e5f526571120d0a0561707049641801200128091212" .
            "0a0a62696756657273696f6e18022001280912140a0c736d616c6c566572" .
            "73696f6e180320012805228b010a1650425f436865636b41707056657273" .
            "696f6e5f52657312120a0a62696756657273696f6e18012001280912140a" .
            "0c736d616c6c56657273696f6e18022001280512120a0a7061636b616765" .
            "55726c18032001280912110a096861735570646174651804200128081213" .
            "0a0b666f726365557064617465180520012808120b0a036d643518062001" .
            "2809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

