<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_CheckAppVersion.proto

namespace GPBMetadata;

class PBCheckAppVersion
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a86020a1850425f436865636b41707056657273696f6e2e70726f746f12" .
            "10475042436c6173732e4d65737361676522420a1650425f436865636b41" .
            "707056657273696f6e5f52657112120a0a62696756657273696f6e180120" .
            "01280912140a0c736d616c6c56657273696f6e180220012805228b010a16" .
            "50425f436865636b41707056657273696f6e5f52657312120a0a62696756" .
            "657273696f6e18012001280912140a0c736d616c6c56657273696f6e1802" .
            "2001280512120a0a7061636b61676555726c18032001280912110a096861" .
            "7355706461746518042001280812130a0b666f7263655570646174651805" .
            "20012808120b0a036d6435180620012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

