<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_CheckModuleVersion.proto

namespace GPBMetadata;

class PBCheckModuleVersion
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8a020a1b50425f436865636b4d6f64756c6556657273696f6e2e70726f" .
            "746f1210475042436c6173732e4d657373616765225f0a1950425f436865" .
            "636b4d6f64756c6556657273696f6e5f526571120d0a0561707049641801" .
            "20012809120e0a066d6f64756c6518022001280912120a0a626967566572" .
            "73696f6e180320012809120f0a0776657273696f6e18042001280522700a" .
            "1950425f436865636b4d6f64756c6556657273696f6e5f526573120e0a06" .
            "6d6f64756c65180120012809120f0a0776657273696f6e18022001280512" .
            "120a0a7061636b61676555726c18032001280912110a0968617355706461" .
            "7465180420012808120b0a036d6435180520012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

