<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_CollectInfo.proto

namespace GPBMetadata;

class PBCollectInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af4010a1450425f436f6c6c656374496e666f2e70726f746f1210475042" .
            "436c6173732e4d65737361676522c1010a0e50425f436f6c6c656374496e" .
            "666f120c0a046e6f646518012001280512110a09756e6c6f636b42657418" .
            "022001280512130a0b636f6c6c6563745479706518032001280912140a0c" .
            "636f6c6c6563744974656d7318042003280912100a08626f6f7374657273" .
            "180520012809120e0a06617667426574180620012803120d0a0576616c75" .
            "6518072001280312100a0870726f6772657373180820012803120e0a0674" .
            "617267657418092001280312100a08636f6d706c657465180a2001280862" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

