<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_ExitMachine.proto

namespace GPBMetadata;

class PBExitMachine
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a6f0a1450425f457869744d616368696e652e70726f746f121047504243" .
            "6c6173732e4d65737361676522140a1250425f457869744d616368696e65" .
            "5f52657122270a1250425f457869744d616368696e655f52657312110a09" .
            "6d616368696e654964180120012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

