<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_FeaturesOver.proto

namespace GPBMetadata;

class PBFeaturesOver
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9a020a1550425f46656174757265734f7665722e70726f746f12104750" .
            "42436c6173732e4d65737361676522150a1350425f46656174757265734f" .
            "7665725f5265712297010a1350425f46656174757265734f7665725f5265" .
            "7312100a08746f74616c57696e18012001280312120a0a66656174757265" .
            "57696e18022001280312380a0d66656174757265735072697a6518032003" .
            "280b32212e475042436c6173732e4d6573736167652e50425f4665617475" .
            "72655072697a65120f0a0777696e54797065180420012805120f0a077365" .
            "74746c656418052001280822360a0f50425f466561747572655072697a65" .
            "12110a0966656174757265496418012001280912100a08636f696e735769" .
            "6e180220012803620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

