<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_FetchWheeItems.proto

namespace GPBMetadata;

class PBFetchWheeItems
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afe010a1750425f4665746368576865654974656d732e70726f746f1210" .
            "475042436c6173732e4d65737361676522280a1550425f46657463685768" .
            "65654974656d735f526571120f0a07776865656c4964180120012809224d" .
            "0a1550425f4665746368576865654974656d735f52657312340a046c6973" .
            "7418012003280b32262e475042436c6173732e4d6573736167652e50425f" .
            "4665746368576865654974656d496e666f22500a1450425f466574636857" .
            "6865654974656d496e666f120c0a046974656d180120012809120b0a0370" .
            "6f73180220012805120d0a0576616c7565180320012809120e0a06776569" .
            "676874180420012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

