<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_FeatureWinInfo.proto

namespace GPBMetadata;

class PBFeatureWinInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac8010a1750425f4665617475726557696e496e666f2e70726f746f1210" .
            "475042436c6173732e4d6573736167652292010a1150425f466561747572" .
            "6557696e496e666f12120a0a6665617475726557696e1801200128031210" .
            "0a08636f696e7357696e18022001280312100a08746f74616c57696e1803" .
            "20012803120f0a0777696e5479706518042001280512120a0a61644d756c" .
            "7469706c65180520012805120f0a077370696e456e64180620012808120f" .
            "0a07736574746c6564180720012808620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

