<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_HoldAndSpin.proto

namespace GPBMetadata;

class PBHoldAndSpin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PBSlotsElement::initOnce();
        \GPBMetadata\PBJackpotPrize::initOnce();
        \GPBMetadata\PBFeatureWinInfo::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af6020a1450425f486f6c64416e645370696e2e70726f746f1210475042" .
            "436c6173732e4d6573736167651a1550425f4a61636b706f745072697a65" .
            "2e70726f746f1a1750425f4665617475726557696e496e666f2e70726f74" .
            "6f22140a1250425f486f6c64416e645370696e5f52657122fd010a125042" .
            "5f486f6c64416e645370696e5f52657312330a08656c656d656e74731801" .
            "2003280b32212e475042436c6173732e4d6573736167652e50425f536c6f" .
            "7473456c656d656e74120e0a0669734f76657218022001280812100a0862" .
            "6f6e757357696e18032001280312380a0d6a61636b706f745072697a6573" .
            "18042003280b32212e475042436c6173732e4d6573736167652e50425f4a" .
            "61636b706f745072697a65120d0a0574696d657318052001280512110a09" .
            "636f6c6c656374656418062001280512340a0777696e496e666f18072001" .
            "280b32232e475042436c6173732e4d6573736167652e50425f4665617475" .
            "726557696e496e666f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

