<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_InitJackpots.proto

namespace GPBMetadata;

class PBInitJackpots
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PBJackpotInfo::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a93010a1550425f496e69744a61636b706f74732e70726f746f12104750" .
            "42436c6173732e4d65737361676522150a1350425f496e69744a61636b70" .
            "6f74735f52657122490a1350425f496e69744a61636b706f74735f526573" .
            "12320a086a61636b706f747318012003280b32202e475042436c6173732e" .
            "4d6573736167652e50425f4a61636b706f74496e666f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

