<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_InitCollect.proto

namespace GPBMetadata;

class PBInitCollect
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PBCollectInfo::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a93010a1450425f496e6974436f6c6c6563742e70726f746f1210475042" .
            "436c6173732e4d65737361676522140a1250425f496e6974436f6c6c6563" .
            "745f526571224b0a1250425f496e6974436f6c6c6563745f52657312350a" .
            "0b636f6c6c656374496e666f18012001280b32202e475042436c6173732e" .
            "4d6573736167652e50425f436f6c6c656374496e666f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

