<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_ItemInfo.proto

namespace GPBMetadata;

class PBItemInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8a010a1150425f4974656d496e666f2e70726f746f1210475042436c61" .
            "73732e4d657373616765225b0a0b50425f4974656d496e666f120e0a0669" .
            "74656d4964180120012809120c0a0474797065180220012805120d0a0563" .
            "6f756e74180320012805120d0a0576616c756518042001280912100a0864" .
            "75726174696f6e180520012803620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

