<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_JackpotPrize.proto

namespace GPBMetadata;

class PBJackpotPrize
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7b0a1550425f4a61636b706f745072697a652e70726f746f1210475042" .
            "436c6173732e4d65737361676522480a0f50425f4a61636b706f74507269" .
            "7a6512110a096a61636b706f74496418012001280912130a0b6a61636b70" .
            "6f744e616d65180220012809120d0a05636f696e73180320012801620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

