<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_JackpotPickGame.proto

namespace GPBMetadata;

class PBJackpotPickGame
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PBFeatureWinInfo::initOnce();
        \GPBMetadata\PBJackpotPrize::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aff020a1850425f4a61636b706f745069636b47616d652e70726f746f12" .
            "10475042436c6173732e4d6573736167651a1550425f4a61636b706f7450" .
            "72697a652e70726f746f22180a1650425f4a61636b706f745069636b4761" .
            "6d655f52657122c4010a1650425f4a61636b706f745069636b47616d655f" .
            "52657312340a0777696e496e666f18012001280b32232e475042436c6173" .
            "732e4d6573736167652e50425f4665617475726557696e496e666f123a0a" .
            "0a7069636b526573756c7418022001280b32262e475042436c6173732e4d" .
            "6573736167652e50425f4a61636b706f745069636b526573756c7412380a" .
            "0d6a61636b706f745072697a657318032003280b32212e475042436c6173" .
            "732e4d6573736167652e50425f4a61636b706f745072697a6522510a1450" .
            "425f4a61636b706f745069636b526573756c7412130a0b6869744a61636b" .
            "506f747318012003280912110a097069636b436172647318022003280912" .
            "110a097069636b54696d6573180320012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

