<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_JackpotInfo.proto

namespace GPBMetadata;

class PBJackpotInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac1020a1450425f4a61636b706f74496e666f2e70726f746f1210475042" .
            "436c6173732e4d657373616765228e020a0e50425f4a61636b706f74496e" .
            "666f12110a096a61636b706f74496418012001280912130a0b6a61636b70" .
            "6f744e616d6518022001280912130a0b6d696e4265744c6576656c180320" .
            "01280512130a0b6d61784265744c6576656c18042001280512120a0a6177" .
            "617264427942657418052001280812120a0a6177617264426567696e1806" .
            "2001280112100a086177617264456e6418072001280112100a0864757261" .
            "74696f6e18082001280312160a0e67726f7774684d756c7469706c651809" .
            "2001280112120a0a63726561746554696d65180a20012803120e0a067461" .
            "72676574180b2001280512100a0870726f6772657373180c200128051210" .
            "0a08756e6c6f636b6564180d20012808620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

