<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_MessageBase64List.proto

namespace GPBMetadata;

class PBMessageBase64List
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a700a1a50425f4d6573736167654261736536344c6973742e70726f746f" .
            "1210475042436c6173732e4d65737361676522380a1450425f4d65737361" .
            "67654261736536344c697374120d0a056d7367496418012001280512110a" .
            "096d7367426173653634180220012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

