<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_NTF_CollectProgress.proto

namespace GPBMetadata;

class PBNTFCollectProgress
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c010a1c50425f4e54465f436f6c6c65637450726f67726573732e7072" .
            "6f746f1210475042436c6173732e4d65737361676522620a1a50425f4e54" .
            "465f436f6c6c65637450726f67726573735f52657312170a0f636f6c6c65" .
            "637450726f677265737318012001280312150a0d636f6c6c656374417667" .
            "42657418022001280312140a0c636f6c6c65637456616c75651803200128" .
            "03620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

