<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_NTF_LevelPrize.proto

namespace GPBMetadata;

class PBNTFLevelPrize
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PBPrizeInfo::initOnce();
        \GPBMetadata\PBBetOption::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af2010a1750425f4e54465f4c6576656c5072697a652e70726f746f1210" .
            "475042436c6173732e4d6573736167651a1250425f4265744f7074696f6e" .
            "2e70726f746f22a8010a1550425f4e54465f4c6576656c5072697a655f52" .
            "6573120b0a03657870180120012803120d0a056c6576656c180220012805" .
            "120f0a076c6576656c5570180320012808122e0a067072697a6573180420" .
            "03280b321e2e475042436c6173732e4d6573736167652e50425f5072697a" .
            "65496e666f12320a0a6265744f7074696f6e7318052003280b321e2e4750" .
            "42436c6173732e4d6573736167652e50425f4265744f7074696f6e620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

