<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_NTF_JackpotPrize.proto

namespace GPBMetadata;

class PBNTFJackpotPrize
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PBJackpotPrize::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8a010a1950425f4e54465f4a61636b706f745072697a652e70726f746f" .
            "1210475042436c6173732e4d65737361676522530a1750425f4e54465f4a" .
            "61636b706f745072697a655f52657312380a0d6a61636b706f745072697a" .
            "657318012003280b32212e475042436c6173732e4d6573736167652e5042" .
            "5f4a61636b706f745072697a65620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

