<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Ping.proto

namespace GPBMetadata;

class PBPing
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5a0a0d50425f50696e672e70726f746f1210475042436c6173732e4d65" .
            "737361676522200a0b50425f50696e675f52657112110a096973506c6179" .
            "696e67180120012805220d0a0b50425f50696e675f526573620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

