<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_PrizeInfo.proto

namespace GPBMetadata;

class PBPrizeInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a7c0a1250425f5072697a65496e666f2e70726f746f1210475042436c61" .
            "73732e4d657373616765224c0a0c50425f5072697a65496e666f120e0a06" .
            "6974656d4964180120012809120c0a0474797065180220012805120d0a05" .
            "636f756e74180320012801120f0a0762616c616e63651804200128016206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

