<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_ResumeFreeGame.proto

namespace GPBMetadata;

class PBResumeFreeGame
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae3010a1750425f526573756d654672656547616d652e70726f746f1210" .
            "475042436c6173732e4d65737361676522170a1550425f526573756d6546" .
            "72656547616d655f5265712294010a1550425f526573756d654672656547" .
            "616d655f52657312110a097370696e54696d657318012001280512120a0a" .
            "746f74616c54696d6573180220012805120e0a0664657461696c18032001" .
            "280912100a08746f74616c42657418042001280312100a08746f74616c57" .
            "696e180520012803120f0a0777696e54797065180620012805120f0a0773" .
            "6574746c6564180720012808620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

