<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_RecoverLightning.proto

namespace GPBMetadata;

class PBRecoverLightning
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PBSlotsElement::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad3010a1950425f5265636f7665724c696768746e696e672e70726f746f" .
            "1210475042436c6173732e4d65737361676522190a1750425f5265636f76" .
            "65724c696768746e696e675f5265712280010a1750425f5265636f766572" .
            "4c696768746e696e675f526573120d0a0574696d65731801200128051211" .
            "0a09636f6c6c6563746564180220012805120e0a06626967436f6c180320" .
            "01280512330a08656c656d656e747318042003280b32212e475042436c61" .
            "73732e4d6573736167652e50425f536c6f7473456c656d656e7462067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

