<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_RoleInfo.proto

namespace GPBMetadata;

class PBRoleInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a97020a1150425f526f6c65496e666f2e70726f746f1210475042436c61" .
            "73732e4d65737361676522e7010a0b50425f526f6c65496e666f120b0a03" .
            "75696418012001280512100a086e69636b6e616d65180220012809120e0a" .
            "06617661746172180320012809120b0a03657870180420012803120d0a05" .
            "6c6576656c180520012805120b0a03766970180620012805120e0a067669" .
            "70507473180720012803120d0a05636f696e73180820012803120f0a0764" .
            "69616d6f6e64180920012805120c0a046c616e67180a2001280912150a0d" .
            "6c6576656c50726f6772657373180b2001280212130a0b76697050726f67" .
            "72657373180c2001280212160a0e706c6174666f726d417661746172180d" .
            "20012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

