<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SetAvatar.proto

namespace GPBMetadata;

class PBSetAvatar
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a760a1250425f5365744176617461722e70726f746f1210475042436c61" .
            "73732e4d65737361676522220a1050425f5365744176617461725f526571" .
            "120e0a0661766174617218012001280922220a1050425f53657441766174" .
            "61725f526573120e0a06617661746172180120012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

