<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SetNickname.proto

namespace GPBMetadata;

class PBSetNickname
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a80010a1450425f5365744e69636b6e616d652e70726f746f1210475042" .
            "436c6173732e4d65737361676522260a1250425f5365744e69636b6e616d" .
            "655f52657112100a086e69636b6e616d6518012001280922260a1250425f" .
            "5365744e69636b6e616d655f52657312100a086e69636b6e616d65180120" .
            "012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

