<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SlotsResultSteps.proto

namespace GPBMetadata;

class PBSlotsResultSteps
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PBSlotsHitResult::initOnce();
        \GPBMetadata\PBSlotsElement::initOnce();
        \GPBMetadata\PBSlotsPrize::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5020a1950425f536c6f7473526573756c7453746570732e70726f746f" .
            "1210475042436c6173732e4d6573736167651a1550425f536c6f7473456c" .
            "656d656e742e70726f746f1a1350425f536c6f74735072697a652e70726f" .
            "746f22d1010a1350425f536c6f7473526573756c745374657073120c0a04" .
            "7374657018012001280512330a08656c656d656e747318022003280b3221" .
            "2e475042436c6173732e4d6573736167652e50425f536c6f7473456c656d" .
            "656e7412340a07726573756c747318032003280b32232e475042436c6173" .
            "732e4d6573736167652e50425f536c6f7473486974526573756c74122f0a" .
            "067072697a657318042001280b321f2e475042436c6173732e4d65737361" .
            "67652e50425f536c6f74735072697a6512100a08746f74616c57696e1805" .
            "20012803620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

