<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SlotsHitResult.proto

namespace GPBMetadata;

class PBSlotsHitResult
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aed010a1750425f536c6f7473486974526573756c742e70726f746f1210" .
            "475042436c6173732e4d65737361676522340a1150425f536c6f74734c69" .
            "6e655072697a65120d0a05636f696e7318012001280312100a086d756c74" .
            "69706c651802200128052281010a1150425f536c6f747348697452657375" .
            "6c74120e0a066c696e65496418012001280912150a096c696e65526f7574" .
            "651802200328054202100112100a08656c656d656e747318032003280912" .
            "330a067072697a657318042001280b32232e475042436c6173732e4d6573" .
            "736167652e50425f536c6f74734c696e655072697a65620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

