<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SlotsPrize.proto

namespace GPBMetadata;

class PBSlotsPrize
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PBSlotsElement::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad6020a1350425f536c6f74735072697a652e70726f746f121047504243" .
            "6c6173732e4d65737361676522c6010a0d50425f536c6f74735072697a65" .
            "120d0a05636f696e7318012001280312100a08667265657370696e180220" .
            "01280512100a086d756c7469706c6518032001280512330a08656c656d65" .
            "6e747318042003280b32212e475042436c6173732e4d6573736167652e50" .
            "425f536c6f7473456c656d656e7412100a08666561747572657318052003" .
            "2809123b0a0d73706c6974456c656d656e747318062003280b32242e4750" .
            "42436c6173732e4d6573736167652e50425f46656174757265456c656d65" .
            "6e7473225c0a1250425f46656174757265456c656d656e747312110a0966" .
            "656174757265496418012001280912330a08656c656d656e747318022003" .
            "280b32212e475042436c6173732e4d6573736167652e50425f536c6f7473" .
            "456c656d656e74620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

