<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_SlotsElement.proto

namespace GPBMetadata;

class PBSlotsElement
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a80010a1550425f536c6f7473456c656d656e742e70726f746f12104750" .
            "42436c6173732e4d657373616765224d0a0f50425f536c6f7473456c656d" .
            "656e7412110a09656c656d656e744964180120012805120b0a03636f6c18" .
            "0220012805120b0a03726f77180320012805120d0a0576616c7565180420" .
            "012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

