<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_TcpPing.proto

namespace GPBMetadata;

class PBTcpPing
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a500a1050425f54637050696e672e70726f746f1210475042436c617373" .
            "2e4d65737361676522100a0e50425f54637050696e675f52657122100a0e" .
            "50425f54637050696e675f526573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

