<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_TcpPausePing.proto

namespace GPBMetadata;

class PBTcpPausePing
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a5f0a1550425f546370506175736550696e672e70726f746f1210475042" .
            "436c6173732e4d65737361676522150a1350425f54637050617573655069" .
            "6e675f52657122150a1350425f546370506175736550696e675f52657362" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

