<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_UserBind.proto

namespace GPBMetadata;

class PBUserBind
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab3010a1150425f5573657242696e642e70726f746f1210475042436c61" .
            "73732e4d65737361676522420a0f50425f5573657242696e645f52657112" .
            "0e0a066f70656e6964180120012809120d0a05746f6b656e180220012809" .
            "12100a08706c6174666f726d18032001280522400a0f50425f5573657242" .
            "696e645f526573120b0a0375696418012001280512100a086e69636b6e61" .
            "6d65180220012809120e0a06617661746172180320012809620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

