<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_WheelItemInfo.proto

namespace GPBMetadata;

class PBWheelItemInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9a010a1650425f576865656c4974656d496e666f2e70726f746f121047" .
            "5042436c6173732e4d65737361676522660a1050425f576865656c497465" .
            "6d496e666f120b0a03706f7318012001280512100a086974656d4e616d65" .
            "18022001280912100a086974656d5479706518032001280912110a096974" .
            "656d56616c7565180420012809120e0a066974656d496418052001280962" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

