<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_WheelSpin.proto

namespace GPBMetadata;

class PBWheelSpin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\PBPrizeInfo::initOnce();
        \GPBMetadata\PBFeatureWinInfo::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa4020a1250425f576865656c5370696e2e70726f746f1210475042436c" .
            "6173732e4d6573736167651a1750425f4665617475726557696e496e666f" .
            "2e70726f746f22300a1050425f576865656c5370696e5f526571120f0a07" .
            "776865656c4964180120012809120b0a03706f7318022001280522a8010a" .
            "1050425f576865656c5370696e5f526573120b0a03706f73180120012805" .
            "122e0a067072697a657318022003280b321e2e475042436c6173732e4d65" .
            "73736167652e50425f5072697a65496e666f12130a0b6e65787457686565" .
            "6c4964180320012809120c0a04636f737418042001280512340a0777696e" .
            "496e666f18052001280b32232e475042436c6173732e4d6573736167652e" .
            "50425f4665617475726557696e496e666f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

