<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Common.proto

namespace GPBClass\Enum;

/**
 * Protobuf enum <code>GPBClass\Enum\BUFF</code>
 */
class BUFF
{
    /**
     *占位NULL
     *
     * Generated from protobuf enum <code>NULL = 0;</code>
     */
    const NULL = 0;
    /**
     *体验VIP
     *
     * Generated from protobuf enum <code>VIP_TRIAL = 1;</code>
     */
    const VIP_TRIAL = 1;
    /**
     *VIP加速
     *
     * Generated from protobuf enum <code>VIP_BOOSTER = 2;</code>
     */
    const VIP_BOOSTER = 2;
    /**
     *等级加速
     *
     * Generated from protobuf enum <code>LEVEL_BURST = 3;</code>
     */
    const LEVEL_BURST = 3;
    /**
     *SPIN积分加速
     *
     * Generated from protobuf enum <code>SPIN_BURST = 4;</code>
     */
    const SPIN_BURST = 4;
    /**
     *金币奖励
     *
     * Generated from protobuf enum <code>COINS_BONUS = 5;</code>
     */
    const COINS_BONUS = 5;
    /**
     *小时奖励加速
     *
     * Generated from protobuf enum <code>HOURLY_BONUS_BURST = 6;</code>
     */
    const HOURLY_BONUS_BURST = 6;
}

