<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Common.proto

namespace GPBClass\Enum;

/**
 * Protobuf enum <code>GPBClass\Enum\ITEM_TYPE</code>
 */
class ITEM_TYPE
{
    /**
     *占位NULL
     *
     * Generated from protobuf enum <code>ITEM_TYPE_NULL = 0;</code>
     */
    const ITEM_TYPE_NULL = 0;
    /**
     *金币
     *
     * Generated from protobuf enum <code>ITEM_TYPE_COINS = 1;</code>
     */
    const ITEM_TYPE_COINS = 1;
    /**
     *Cash
     *
     * Generated from protobuf enum <code>ITEM_TYPE_CASH = 2;</code>
     */
    const ITEM_TYPE_CASH = 2;
    /**
     *经验
     *
     * Generated from protobuf enum <code>ITEM_TYPE_EXP = 3;</code>
     */
    const ITEM_TYPE_EXP = 3;
    /**
     *VIP积分
     *
     * Generated from protobuf enum <code>ITEM_TYPE_VIP_PTS = 4;</code>
     */
    const ITEM_TYPE_VIP_PTS = 4;
    /**
     *SPIN积分
     *
     * Generated from protobuf enum <code>ITEM_TYPE_SPIN_PTS = 5;</code>
     */
    const ITEM_TYPE_SPIN_PTS = 5;
    /**
     *FreeSpin
     *
     * Generated from protobuf enum <code>ITEM_TYPE_FREE_SPIN = 6;</code>
     */
    const ITEM_TYPE_FREE_SPIN = 6;
    /**
     *任务积分
     *
     * Generated from protobuf enum <code>ITEM_TYPE_TASK_PTS = 7;</code>
     */
    const ITEM_TYPE_TASK_PTS = 7;
    /**
     *Feature
     *
     * Generated from protobuf enum <code>ITEM_TYPE_FEATURE = 8;</code>
     */
    const ITEM_TYPE_FEATURE = 8;
    /**
     *Wheel
     *
     * Generated from protobuf enum <code>ITEM_TYPE_WHEEL = 9;</code>
     */
    const ITEM_TYPE_WHEEL = 9;
    /**
     *jackpot
     *
     * Generated from protobuf enum <code>ITEM_TYPE_JACKPOT = 10;</code>
     */
    const ITEM_TYPE_JACKPOT = 10;
}

