<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Common.proto

namespace GPBClass\Enum;

/**
 * Protobuf enum <code>GPBClass\Enum\MSG_ID</code>
 */
class MSG_ID
{
    /**
     *占位NULL
     *
     * Generated from protobuf enum <code>MSG_NULL = 0;</code>
     */
    const MSG_NULL = 0;
    /**
     *检查应用版本
     *
     * Generated from protobuf enum <code>MSG_CHECK_APP_VERSION = 1001;</code>
     */
    const MSG_CHECK_APP_VERSION = 1001;
    /**
     *检查模块版本
     *
     * Generated from protobuf enum <code>MSG_CHECK_MODULE_VERSION = 1002;</code>
     */
    const MSG_CHECK_MODULE_VERSION = 1002;
    /**
     *事件上报
     *
     * Generated from protobuf enum <code>MSG_EVENT_REPORT = 1003;</code>
     */
    const MSG_EVENT_REPORT = 1003;
    /**
     *PING
     *
     * Generated from protobuf enum <code>MSG_PING = 1004;</code>
     */
    const MSG_PING = 1004;
    /**
     *用户登录
     *
     * Generated from protobuf enum <code>MSG_USER_LOGIN = 2000;</code>
     */
    const MSG_USER_LOGIN = 2000;
    /**
     *用户绑定
     *
     * Generated from protobuf enum <code>MSG_USER_BIND = 2001;</code>
     */
    const MSG_USER_BIND = 2001;
    /**
     *设置用户昵称
     *
     * Generated from protobuf enum <code>MSG_SET_USER_NICKNAME = 2002;</code>
     */
    const MSG_SET_USER_NICKNAME = 2002;
    /**
     *设置用户头像
     *
     * Generated from protobuf enum <code>MSG_SET_USER_AVATAR = 2003;</code>
     */
    const MSG_SET_USER_AVATAR = 2003;
    /**
     *进入机台
     *
     * Generated from protobuf enum <code>MSG_ENTER_MACHINE = 3001;</code>
     */
    const MSG_ENTER_MACHINE = 3001;
    /**
     *退出机台
     *
     * Generated from protobuf enum <code>MSG_EXIT_MACHINE = 3002;</code>
     */
    const MSG_EXIT_MACHINE = 3002;
    /**
     *机台jackpot初始化
     *
     * Generated from protobuf enum <code>MSG_INIT_JACKPOTS = 3003;</code>
     */
    const MSG_INIT_JACKPOTS = 3003;
    /**
     *机台下注
     *
     * Generated from protobuf enum <code>MSG_SLOTS_BETTING = 3004;</code>
     */
    const MSG_SLOTS_BETTING = 3004;
    /**
     *机台收集初始化
     *
     * Generated from protobuf enum <code>MSG_INIT_COLLECT_GAME = 3005;</code>
     */
    const MSG_INIT_COLLECT_GAME = 3005;
    /**
     *恢复FreeGame
     *
     * Generated from protobuf enum <code>MSG_RESUME_FREEGAME = 4001;</code>
     */
    const MSG_RESUME_FREEGAME = 4001;
    /**
     *恢复Lightning
     *
     * Generated from protobuf enum <code>MSG_RECOVER_LIGHTNING = 4002;</code>
     */
    const MSG_RECOVER_LIGHTNING = 4002;
    /**
     *Hold&Spin
     *
     * Generated from protobuf enum <code>MSG_HOLD_AND_SPIN = 4003;</code>
     */
    const MSG_HOLD_AND_SPIN = 4003;
    /**
     *转盘SPIN
     *
     * Generated from protobuf enum <code>MSG_WHEEL_SPIN = 4004;</code>
     */
    const MSG_WHEEL_SPIN = 4004;
    /**
     *进行pickGame
     *
     * Generated from protobuf enum <code>MSG_PLAY_PICK_GAME = 4005;</code>
     */
    const MSG_PLAY_PICK_GAME = 4005;
    /**
     *结束所有feature
     *
     * Generated from protobuf enum <code>MSG_FEATURES_OVER = 4006;</code>
     */
    const MSG_FEATURES_OVER = 4006;
    /**
     *等级奖励通知
     *
     * Generated from protobuf enum <code>MSG_NTF_LEVEL_PRIZE = 7001;</code>
     */
    const MSG_NTF_LEVEL_PRIZE = 7001;
    /**
     *Jackpot奖励通知()
     *
     * Generated from protobuf enum <code>MSG_NTF_JACKPOT_PRIZE = 7002;</code>
     */
    const MSG_NTF_JACKPOT_PRIZE = 7002;
    /**
     *收集进度通知
     *
     * Generated from protobuf enum <code>MSG_NTF_COLLECT_PROGRESS = 7003;</code>
     */
    const MSG_NTF_COLLECT_PROGRESS = 7003;
}

