<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Common.proto

namespace GPBClass\Enum;

/**
 * Protobuf enum <code>GPBClass\Enum\PAY_CHANNEL</code>
 */
class PAY_CHANNEL
{
    /**
     *GOOGLE PLAY
     *
     * Generated from protobuf enum <code>PAY_CHANNEL_GOOGLE_PLAY = 0;</code>
     */
    const PAY_CHANNEL_GOOGLE_PLAY = 0;
    /**
     *APPLE STORE
     *
     * Generated from protobuf enum <code>PAY_CHANNEL_APPLE_STORE = 1;</code>
     */
    const PAY_CHANNEL_APPLE_STORE = 1;
}

