<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Common.proto

namespace GPBClass\Enum;

/**
 * Protobuf enum <code>GPBClass\Enum\PLATFORM</code>
 */
class PLATFORM
{
    /**
     *游客
     *
     * Generated from protobuf enum <code>PLATFORM_GUEST = 0;</code>
     */
    const PLATFORM_GUEST = 0;
    /**
     *Facebook
     *
     * Generated from protobuf enum <code>PLATFORM_FACEBOOK = 1;</code>
     */
    const PLATFORM_FACEBOOK = 1;
    /**
     *apple
     *
     * Generated from protobuf enum <code>PLATFORM_APPLE = 3;</code>
     */
    const PLATFORM_APPLE = 3;
}

