<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Common.proto

namespace GPBClass\Enum;

/**
 * Protobuf enum <code>GPBClass\Enum\RET</code>
 */
class RET extends \FF\Framework\Common\Code
{
    /**
     *成功
     *
     * Generated from protobuf enum <code>RET_SUCCESS = 0;</code>
     */
    const RET_SUCCESS = 0;
    /**
     *失败
     *
     * Generated from protobuf enum <code>RET_FAILED = 1;</code>
     */
    const RET_FAILED = 1;
    /**
     *系统错误
     *
     * Generated from protobuf enum <code>RET_SYSTEM_ERROR = 2;</code>
     */
    const RET_SYSTEM_ERROR = 2;
    /**
     *客户端超时
     *
     * Generated from protobuf enum <code>RET_CLIENT_TIMEOUT = 99;</code>
     */
    const RET_CLIENT_TIMEOUT = 99;
    /**
     *系统维护中
     *
     * Generated from protobuf enum <code>RET_SYSTEM_MAINTAIN = 1001;</code>
     */
    const RET_SYSTEM_MAINTAIN = 1001;
    /**
     *版本过低
     *
     * Generated from protobuf enum <code>RET_VERSION_TOO_OLD = 1002;</code>
     */
    const RET_VERSION_TOO_OLD = 1002;
    /**
     *请求过于频繁
     *
     * Generated from protobuf enum <code>RET_REQUEST_TO_FREQUENT = 1003;</code>
     */
    const RET_REQUEST_TO_FREQUENT = 1003;
    /**
     *Session无效
     *
     * Generated from protobuf enum <code>RET_SESSION_INVALID = 1011;</code>
     */
    const RET_SESSION_INVALID = 1011;
    /**
     *MSG_ID无效
     *
     * Generated from protobuf enum <code>RET_MSG_ID_INVALID = 1012;</code>
     */
    const RET_MSG_ID_INVALID = 1012;
    /**
     *MSG内容为空
     *
     * Generated from protobuf enum <code>RET_MSG_IS_NULL = 1013;</code>
     */
    const RET_MSG_IS_NULL = 1013;
    /**
     *MSG解码失败
     *
     * Generated from protobuf enum <code>RET_MSG_DECODE_FAILED = 1014;</code>
     */
    const RET_MSG_DECODE_FAILED = 1014;
    /**
     *MSG编码失败
     *
     * Generated from protobuf enum <code>RET_MSG_ENCODE_FAILED = 1015;</code>
     */
    const RET_MSG_ENCODE_FAILED = 1015;
    /**
     *Token无效
     *
     * Generated from protobuf enum <code>RET_TOKEN_INVALID = 1020;</code>
     */
    const RET_TOKEN_INVALID = 1020;
    /**
     *账号不存在
     *
     * Generated from protobuf enum <code>RET_ACCOUNT_NOT_EXIST = 1021;</code>
     */
    const RET_ACCOUNT_NOT_EXIST = 1021;
    /**
     *账号已经存在
     *
     * Generated from protobuf enum <code>RET_ACCOUNT_EXIST = 1022;</code>
     */
    const RET_ACCOUNT_EXIST = 1022;
    /**
     *账号长度不符合要求
     *
     * Generated from protobuf enum <code>RET_ACCOUNT_LEN_INVALID = 1023;</code>
     */
    const RET_ACCOUNT_LEN_INVALID = 1023;
    /**
     *密码长度不符合要求
     *
     * Generated from protobuf enum <code>RET_PASSWORD_LEN_INVALID = 1024;</code>
     */
    const RET_PASSWORD_LEN_INVALID = 1024;
    /**
     *密码输入错误
     *
     * Generated from protobuf enum <code>RET_PASSWORD_INCORRECT = 1025;</code>
     */
    const RET_PASSWORD_INCORRECT = 1025;
    /**
     *账号创建失败
     *
     * Generated from protobuf enum <code>RET_ACCOUNT_CREATE_FAILED = 1026;</code>
     */
    const RET_ACCOUNT_CREATE_FAILED = 1026;
    /**
     *账号禁止登录
     *
     * Generated from protobuf enum <code>RET_ACCOUNT_FORBIDDEN = 1027;</code>
     */
    const RET_ACCOUNT_FORBIDDEN = 1027;
    /**
     *昵称为空
     *
     * Generated from protobuf enum <code>RET_NICKNAME_IS_NULL = 1028;</code>
     */
    const RET_NICKNAME_IS_NULL = 1028;
    /**
     *昵称太长
     *
     * Generated from protobuf enum <code>RET_NICKNAME_TOO_LONG = 1029;</code>
     */
    const RET_NICKNAME_TOO_LONG = 1029;
    /**
     *账号重复绑定
     *
     * Generated from protobuf enum <code>RET_ACCOUNT_BIND_REPEAT = 1030;</code>
     */
    const RET_ACCOUNT_BIND_REPEAT = 1030;
    /**
     *等级不足
     *
     * Generated from protobuf enum <code>RET_LEVEL_NOT_ENOUGH = 1031;</code>
     */
    const RET_LEVEL_NOT_ENOUGH = 1031;
    /**
     *金币不足
     *
     * Generated from protobuf enum <code>RET_COINS_NOT_ENOUGH = 1032;</code>
     */
    const RET_COINS_NOT_ENOUGH = 1032;
    /**
     *宝石不足
     *
     * Generated from protobuf enum <code>RET_DIAMOND_NOT_ENOUGH = 1033;</code>
     */
    const RET_DIAMOND_NOT_ENOUGH = 1033;
    /**
     *物品不足
     *
     * Generated from protobuf enum <code>RET_ITEM_NOT_ENOUGH = 1034;</code>
     */
    const RET_ITEM_NOT_ENOUGH = 1034;
    /**
     *金币太多
     *
     * Generated from protobuf enum <code>RET_COINS_TOO_MUCH = 1035;</code>
     */
    const RET_COINS_TOO_MUCH = 1035;
    /**
     *进度不足
     *
     * Generated from protobuf enum <code>RET_PROGRESS_NOT_ENOUGH = 1036;</code>
     */
    const RET_PROGRESS_NOT_ENOUGH = 1036;
    /**
     *机台不存在
     *
     * Generated from protobuf enum <code>RET_MACHINE_NOT_EXIST = 1070;</code>
     */
    const RET_MACHINE_NOT_EXIST = 1070;
    /**
     *下注倍率无效
     *
     * Generated from protobuf enum <code>RET_TOTAL_BET_INVALID = 1071;</code>
     */
    const RET_TOTAL_BET_INVALID = 1071;
    /**
     *下注倍率未激活
     *
     * Generated from protobuf enum <code>RET_TOTAL_BET_DISABLED = 1072;</code>
     */
    const RET_TOTAL_BET_DISABLED = 1072;
}

