<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PB_Common.proto

namespace GPBClass\Enum;

/**
 * Protobuf enum <code>GPBClass\Enum\WIN_TYPE</code>
 */
class WIN_TYPE
{
    /**
     *占位NULL
     *
     * Generated from protobuf enum <code>WIN_TYPE_NULL = 0;</code>
     */
    const WIN_TYPE_NULL = 0;
    /**
     *BIG WIN
     *
     * Generated from protobuf enum <code>WIN_TYPE_BIG_WIN = 1;</code>
     */
    const WIN_TYPE_BIG_WIN = 1;
    /**
     *MEGA WIN
     *
     * Generated from protobuf enum <code>WIN_TYPE_MEGA_WIN = 2;</code>
     */
    const WIN_TYPE_MEGA_WIN = 2;
    /**
     *HUGE WIN
     *
     * Generated from protobuf enum <code>WIN_TYPE_HUGE_WIN = 3;</code>
     */
    const WIN_TYPE_HUGE_WIN = 3;
    /**
     *EPIC WIN
     *
     * Generated from protobuf enum <code>WIN_TYPE_EPIC_WIN = 4;</code>
     */
    const WIN_TYPE_EPIC_WIN = 4;
}

